### PR TITLE
Fix type assert panic in setCAChain()

### LINKED ISSUE #1357: Panic in vault_pki_secret_backend_root_sign_intermediate for ca_chain
### Terraform Version
Terraform v1.1.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/vault v3.3.0

### Affected Resource(s)
vault_pki_secret_backend_root_sign_intermediate

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
Code which I am using is from https://learn.hashicorp.com/tutorials/vault/pki-engine-external-ca

affected part below
```hcl
resource "vault_mount" "test_org_v1_ica2_v1" {
 path                      = "test-org/v1/ica2/v1"
 type                      = "pki"
 description               = "PKI engine hosting intermediate CA2 v1 for test org"
 default_lease_ttl_seconds = local.default_1hr_in_sec
 max_lease_ttl_seconds     = local.default_1y_in_sec
}

resource "vault_pki_secret_backend_intermediate_cert_request" "test_org_v1_ica2_v1" {
 depends_on   = [vault_mount.test_org_v1_ica2_v1]
 backend      = vault_mount.test_org_v1_ica2_v1.path
 type         = "internal"
 common_name  = "Intermediate CA2 v1 "
 key_type     = "rsa"
 key_bits     = "2048"
 ou           = "test org"
 organization = "test"
 country      = "US"
 locality     = "Bethesda"
 province     = "MD"
}

resource "vault_pki_secret_backend_root_sign_intermediate" "test_org_v1_sign_ica2_v1_by_ica1_v1" {
 depends_on = [
  vault_mount.test_org_v1_ica1_v1,
  vault_pki_secret_backend_intermediate_cert_request.test_org_v1_ica2_v1,
 ]
 backend              = vault_mount.test_org_v1_ica1_v1.path
 csr                  = vault_pki_secret_backend_intermediate_cert_request.test_org_v1_ica2_v1.csr
 common_name          = "Intermediate CA2 v1.1"
 exclude_cn_from_sans = true
 ou                   = "test org"
 organization         = "test"
 country              = "US"
 locality             = "Bethesda"
 province             = "MD"
 max_path_length      = "1"
 ttl                  = local.default_1y_in_sec
}

resource "vault_pki_secret_backend_intermediate_set_signed" "test_org_v1_ica2_v1_signed_cert" {
 depends_on  = [vault_pki_secret_backend_root_sign_intermediate.test_org_v1_sign_ica2_v1_by_ica1_v1]
 backend     = vault_mount.test_org_v1_ica2_v1.path
 certificate = format("%s\n%s", vault_pki_secret_backend_root_sign_intermediate.test_org_v1_sign_ica2_v1_by_ica1_v1.certificate, file("../${path.module}/cacerts/test_org_v1_ica1_v1.crt"))
}
```

### Debug Output
https://gist.github.com/lukasz-bielinski/6b51fd30f913778518026f514f42cbb4

### Panic Output
https://gist.github.com/lukasz-bielinski/f27241de6bafd4243fa2d8287988fe6d

### Expected Behavior
resource vault_pki_secret_backend_root_sign_intermediate should be created

### Actual Behavior
panic error in terraform-provider-vault_v3.3.0_x4 plugin:

### Steps to Reproduce
execute steps from https://learn.hashicorp.com/tutorials/vault/pki-engine-external-ca

### Important Factoids
none

### References
https://learn.hashicorp.com/tutorials/vault/pki-engine-external-ca

### PR DESCRIPTION
**Pull request by benashz**
Ensure that the provider does not panic when handling the `ca_chain`.

Add extensive unit tests for `setCAChain()`.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #1357 

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vault/blob/master/CHANGELOG.md):

```release-note

```

Output from acceptance testing:

```
$ make testacc TESTARGS='-v -test.run Test_setCAChain'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test -v -v -test.run Test_setCAChain -timeout 30m ./...

ok      github.com/hashicorp/terraform-provider-vault/util      0.674s [no tests to run]
=== RUN   Test_setCAChain
=== RUN   Test_setCAChain/empty-ca-chain
=== RUN   Test_setCAChain/absent-ca-chain
=== RUN   Test_setCAChain/populated-ca-chain
=== RUN   Test_setCAChain/invalid-ca-chain-type
=== RUN   Test_setCAChain/missing-intermediate-cert
=== RUN   Test_setCAChain/missing-issuing-ca
--- PASS: Test_setCAChain (0.00s)
    --- PASS: Test_setCAChain/empty-ca-chain (0.00s)
    --- PASS: Test_setCAChain/absent-ca-chain (0.00s)
    --- PASS: Test_setCAChain/populated-ca-chain (0.00s)
    --- PASS: Test_setCAChain/invalid-ca-chain-type (0.00s)
    --- PASS: Test_setCAChain/missing-intermediate-cert (0.00s)
    --- PASS: Test_setCAChain/missing-issuing-ca (0.00s)
PASS
ok      github.com/hashicorp/terraform-provider-vault/vault     2.932s

[...]

$ make testacc TESTARGS='-v -test.run TestPkiSecretBackendRootSignIntermediate'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test -v -v -test.run TestPkiSecretBackendRootSignIntermediate -timeout 30m ./...

ok      github.com/hashicorp/terraform-provider-vault/util      (cached) [no tests to run]
=== RUN   TestPkiSecretBackendRootSignIntermediate_basic_default
--- PASS: TestPkiSecretBackendRootSignIntermediate_basic_default (5.03s)
=== RUN   TestPkiSecretBackendRootSignIntermediate_basic_pem
--- PASS: TestPkiSecretBackendRootSignIntermediate_basic_pem (2.45s)
=== RUN   TestPkiSecretBackendRootSignIntermediate_basic_der
--- PASS: TestPkiSecretBackendRootSignIntermediate_basic_der (3.19s)
=== RUN   TestPkiSecretBackendRootSignIntermediate_basic_pem_bundle
--- PASS: TestPkiSecretBackendRootSignIntermediate_basic_pem_bundle (3.41s)
PASS
ok      github.com/hashicorp/terraform-provider-vault/vault     14.564s

```

### CODE REVIEW

File: vault/resource_pki_secret_backend_root_sign_intermediate.go [hunk 1]
```diff
@@ -303,7 +303,14 @@ func setCAChain(d *schema.ResourceData, resp *api.Secret) error {
 	field := "ca_chain"
 	var caChain []string
 	if v, ok := resp.Data[field]; ok && v != nil {
-		caChain = v.([]string)
+		switch v := v.(type) {
```
Comment (vinay-gopalan) [inline vault/resource_pki_secret_backend_root_sign_intermediate.go:306]: Wanted to confirm, was this always returned as `[]interface{}` or was it previously being returned as `[]string` and the behavior changed recently?

**Review by vinay-gopalan — APPROVED** [review]
LGTM!
