### PR TITLE
Fix bug where provider_config only used strings

### LINKED ISSUE #957: vault_jwt_auth_backend for type oidc: provider_config is parsing everything as String
Hello, 

following PR [943](https://github.com/hashicorp/terraform-provider-vault/pull/943), and comments there, I face the following issue. 

When trying to create a vault_jwt_auth_backend with oidc type for gsuite (documentation guide [here](https://www.vaultproject.io/docs/auth/jwt_oidc_providers), everything in "provider_config" gets parsed as String. This means that the boolean variables "fetch_groups" & "fetch_user_info" and the int variable "groups_recurse_max_depth" can not be used, as their respective value types are expected.

In addition, trying to customize/edit the provider I have stumbled upon an issue which may be a code bug, so I am reporting this as well. See below.

### Terraform Version

```
terraform -v                                                         
Terraform v0.14.4
Your version of Terraform is out of date! The latest version
is 0.14.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)
Please list the resources as a list, for example:
`vault_jwt_auth_backend`

### Terraform Configuration Files
```
resource "vault_jwt_auth_backend" "this" {
  path                                = "oidc"
  type                                = "oidc"
  oidc_discovery_url         = "https://accounts.google.com"
  oidc_client_id                 =  "xxxxxx.apps.googleusercontent.com"
  oidc_client_secret          =  "xxxxxx"
  default_role                    = "xxxxxx"
  provider_config = {
    provider                                = "gsuite"
    gsuite_service_account       = "/path/to/service-account.json"
    gsuite_admin_impersonate  = "xxx@xxxxxx.com"
    fetch_groups                        = true
    fetch_user_info                    = true
    groups_recurse_max_depth = 5
  }
}
```

### Debug Output
See below.

### Expected Behavior
Ideally, the oidc backend should be created, with the correct configuration.

### Actual Behavior
```
  + resource "vault_jwt_auth_backend" "this" {
      + accessor           = (known after apply)
      + default_role       = "readonly"
      + id                 = (known after apply)
      + oidc_client_id     = "xxxxxxx"
      + oidc_client_secret = (sensitive value)
      + oidc_discovery_url = "xxxxxxx"
      + path               = "oidc"
      + provider_config    = {
          + "fetch_groups"             = "true"
          + "fetch_user_info"          = "true"
          + "groups_recurse_max_depth" = "5"
          + "gsuite_admin_impersonate" = "xxxxxx"
          + "gsuite_service_account"   = "/etc/config/vault-sa-key.json"
          + "provider"                 = "gsuite"
        }
      + tune               = (known after apply)
      + type               = "oidc"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

vault_jwt_auth_backend.this: Creating...

Error: error updating configuration to Vault for path oidc: Error making API request.

URL: PUT https://xxxxxxxxxxxxxx/v1/auth/oidc/config

Code: 400. Errors:

* invalid provider_config: error initializing "gsuite" provider_config: 3 error(s) decoding:

* 'fetch_groups' expected type 'bool', got unconvertible type 'string'
* 'fetch_user_info' expected type 'bool', got unconvertible type 'string'
* 'groups_recurse_max_depth' expected type 'int', got unconvertible type 'string'

  on main.tf line 1, in resource "vault_jwt_auth_backend" "this":
   1: resource "vault_jwt_auth_backend" "this" {
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Attempt to create a oidc auth backend of type gsuite.

### Important Factoids
I have attempted to fix the issue in [WIP: PR 953](https://github.com/hashicorp/terraform-provider-vault/pull/953), but another error is thrown:
```
2021-01-26T11:49:39.481+0200 [DEBUG] plugin.terraform-provider-vault_v2.18.0_x4: 2021/01/26 11:49:39 [DEBUG] Updating auth oidc2 in Vault
2021/01/26 11:49:39 [DEBUG] vault_jwt_auth_backend.this: apply errored, but we're indicating that via the Error pointer rather than returning it: error updating configuration to Vault for path oidc2: json: unsupported type: schema.SchemaSetFunc
2021/01/26 11:49:39 [TRACE] EvalMaybeTainted: vault_jwt_auth_backend.this encountered an error during creation, so it is now marked as tainted
2021/01/26 11:49:39 [TRACE] EvalWriteState: recording 0 dependencies for vault_jwt_auth_backend.this
2021/01/26 11:49:39 [TRACE] EvalWriteState: writing current state object for vault_jwt_auth_backend.this
2021/01/26 11:49:39 [TRACE] EvalApplyProvisioners: vault_jwt_auth_backend.this is tainted, so skipping provisioning
2021/01/26 11:49:39 [TRACE] EvalMaybeTainted: vault_jwt_auth_backend.this was already tainted, so nothing to do
2021/01/26 11:49:39 [TRACE] EvalWriteState: recording 0 dependencies for vault_jwt_auth_backend.this
2021/01/26 11:49:39 [TRACE] EvalWriteState: writing current state object for vault_jwt_auth_backend.this
2021/01/26 11:49:39 [TRACE] vertex "vault_jwt_auth_backend.this": visit complete
2021/01/26 11:49:39 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/vault\"] (close)" errored, so skipping
2021/01/26 11:49:39 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/01/26 11:49:39 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/01/26 11:49:39 [TRACE] statemgr.Filesystem: creating backup snapshot at terraform.tfstate.backup
2021/01/26 11:49:39 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 5
2021/01/26 11:49:39 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate

2021/01/26 11:49:39 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2021/01/26 11:49:39 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
Error: error updating configuration to Vault for path oidc2: json: unsupported type: schema.SchemaSetFunc

on main.tf line 13, in resource "vault_jwt_auth_backend" "this":
13: resource "vault_jwt_auth_backend" "this" {
```

### References
https://github.com/hashicorp/terraform-provider-vault/pull/953
https://github.com/hashicorp/terraform-provider-vault/pull/943
https://github.com/hashicorp/terraform-provider-vault/issues/828

### PR DESCRIPTION
**Pull request by jasonodonnell**
A bug was recently introduced with the new `provider_config` parameter because the `TypeMap` was casting everything to a string. This parameter can have mixed types, like when configuring GSuite.

This updates the `provider_config` to support all known `provider_config` settings.

Currently the tests pass but when testing gsuite, the backend actually tries to open and verify the JSON service account file. Since we're using a remote docker host which we don't have access to, its currently not possible to check this without auth engine changes or switching to a machine executor. I'll circle back to this next week and wrap up the testing changes.

Fixes #957.

### CODE REVIEW

File: vault/resource_jwt_auth_backend.go [hunk 1]
```diff
@@ -172,6 +202,20 @@ var (
...
+	}
+
+	if v, ok := d.GetOk(prefix + "username"); ok {
+		data["username"] = v.(string)
+	}
+
+	if v, ok := d.GetOk(prefix + "password"); ok {
+		data["password"] = v.(string)
+	}
+}
```
Comment (tvoran) [inline vault/resource_jwt_auth_backend.go:217]: Is this function being used?

File: vault/resource_jwt_auth_backend.go [hunk 2]
```diff
@@ -263,7 +307,24 @@ func jwtAuthBackendRead(d *schema.ResourceData, meta interface{}) error {
...
-		d.Set(configOption, config.Data[configOption])
+
+		if configOption == "provider_config" {
+			var keys []string
+			rawProviderConfig := config.Data[configOption].(map[string]interface{})
+			for k := range rawProviderConfig {
+				keys = append(keys, k)
+			}
+
+			sort.Sort(sort.StringSlice(keys))
```
Comment (tvoran) [inline vault/resource_jwt_auth_backend.go:318]: I think this could be sort.Strings():
```suggestion
			sort.Strings(keys)
```

Though I'm curious why the provider_config keys need to be sorted. Does it have something to do with HasChanged()?

**Comment by tx-kstav** [comment]
Hey @jasonodonnell, just tested this and it works! The oidc backend gets created correctly, I can use it to log in to Vault. I am not sure about @tvoran 's comments, but thank you for the quick work :) 
Looking forward to this getting merged before the next release!

Let me know if you need anything tested (or double/triple tested).

File: .circleci/config.yml [hunk 3]
```diff
@@ -20,6 +20,7 @@ jobs:
       - run:
           name: Wait for containers to starts
           command: dockerize -wait http://127.0.0.1:8200 -wait tcp://127.0.0.1:3306 -timeout 30s
+      - run:
```
Comment (tomhjp) [inline .circleci/config.yml:23]: Is this an accidental change?

File: vault/resource_jwt_auth_backend_test.go [hunk 4]
```diff
@@ -72,6 +72,52 @@ func TestAccJWTAuthBackend_OIDC(t *testing.T) {
...
+					resource.TestCheckResourceAttr("vault_jwt_auth_backend.azure", "oidc_discovery_url", "https://accounts.google.com"),
+					resource.TestCheckResourceAttr("vault_jwt_auth_backend.azure", "provider_config.#", "1"),
+					resource.TestCheckResourceAttr("vault_jwt_auth_backend.azure", "provider_config.2995719985.provider", "azure"),
+				),
+			},
+		},
+	})
+}
+
+// The random numbers on the provider_config are a hash of the object.
```
Comment (tomhjp) [inline vault/resource_jwt_auth_backend_test.go:95]: Is it worth leaving a quick instruction on how to regenerate the new hash if someone needs to change the object under test?

File: vault/resource_jwt_auth_backend.go (hunk 1 above)
Comment (jasonodonnell) [reply vault/resource_jwt_auth_backend.go:217]: Doesn't appear so, removed.

File: vault/resource_jwt_auth_backend.go (hunk 2 above)
Comment (jasonodonnell) [reply vault/resource_jwt_auth_backend.go:318]: Yeah, the sort is required for the hash computed by Terraform. I'll add a comment about this.

Comment (jasonodonnell) [reply vault/resource_jwt_auth_backend.go:318]: Sorting worked and I added a comment.

File: .circleci/config.yml (hunk 3 above)
Comment (jasonodonnell) [reply .circleci/config.yml:23]: Oops, yeah, I was trying some stuff and missed this :)

File: vault/resource_jwt_auth_backend_test.go (hunk 4 above)
Comment (jasonodonnell) [reply vault/resource_jwt_auth_backend_test.go:95]: Actually, I'm going to add a function to calculate it because I had to do some hacky stuff to get the answer.

**Review by tomhjp — APPROVED** [review]

File: vault/resource_jwt_auth_backend_test.go (hunk 4 above)
Comment (jasonodonnell) [reply vault/resource_jwt_auth_backend_test.go]: Added a hashing function in.

Comment (jasonodonnell) [reply vault/resource_jwt_auth_backend_test.go:95]: Unfortunately there were issues with the hashing function, so I reverted this. I'll make a note internally how I got this hash. With the Terraform v2 SDK this is no longer needed so once we upgrade we can clean this up.

File: vault/resource_jwt_auth_backend_test.go [hunk 5]
```diff
@@ -72,6 +72,61 @@ func TestAccJWTAuthBackend_OIDC(t *testing.T) {
...
+		PreCheck:     func() { testJWTLocal(t) },
+		Providers:    testProviders,
+		CheckDestroy: testJWTAuthBackend_Destroyed(path),
+		Steps: []resource.TestStep{
+			{
+				Config: testAccJWTAuthBackendConfigOIDCProviderConfigGSuite(path),
+				Check: resource.ComposeTestCheckFunc(
+					resource.TestCheckResourceAttr("vault_jwt_auth_backend.gsuite", "oidc_discovery_url", "https://accounts.google.com"),
+					resource.TestCheckResourceAttr("vault_jwt_auth_backend.gsuite", "provider_config.1247099397.provider", "gsuite"),
+					resource.TestCheckResourceAttr("vault_jwt_auth_backend.gsuite", "provider_config.1247099397.gsuite_service_account", "/tmp/service-account.json"),
```
Comment (tvoran) [inline vault/resource_jwt_auth_backend_test.go:118]: How about reading the path to the service account file from an env variable, so that it isn't hardcoded to one location? That could even be the condition for skipping this test, similar to what's done elsewhere for MYSQL_URL: https://github.com/hashicorp/terraform-provider-vault/blob/3e79768a0c205ae6788653ca16e0fb3034e4f0d0/vault/resource_database_secret_backend_connection_test.go#L241-L244

File: vault/resource_jwt_auth_backend_test.go [hunk 6]
```diff
@@ -72,6 +72,61 @@ func TestAccJWTAuthBackend_OIDC(t *testing.T) {
...
+// TODO: OIDC plugin has a validation stage when configs are written,
+// and since we use circleci Docker, we can't mount files nor can it see a
+// local one. This will need to be updated when we switch to a Circle machine
+// executor.
+
+// The random numbers on the provider_config are a hash of the object.
+func TestAccJWTAuthBackend_OIDC_Provider_ConfigAzure(t *testing.T) {
+	path := acctest.RandomWithPrefix("oidc")
+	resource.Test(t, resource.TestCase{
+		PreCheck:     func() { testJWTLocal(t) },
```
Comment (tvoran) [inline vault/resource_jwt_auth_backend_test.go:84]: The azure provider_config doesn't do anything in the initialization, so it doesn't need to be skipped in CI. 

(The diff looks strange here, but I'm just suggesting to remove the todo comment block, and replace the PreCheck call to `testJWTLocal(t)` with `testAccPreCheck(t)`.)
 
```suggestion
// The random numbers on the provider_config are a hash of the object.
func TestAccJWTAuthBackend_OIDC_Provider_ConfigAzure(t *testing.T) {
	path := acctest.RandomWithPrefix("oidc")
	resource.Test(t, resource.TestCase{
		PreCheck:     func() { testAccPreCheck(t) },
```

**Comment by bluemalkin** [comment]
Any chance of merging this ?

**Comment by thorfour** [comment]
Just ran into this bug, any chance this gets merged soon?

File: vault/resource_jwt_auth_backend_test.go (hunk 5 above)
Comment (jasonodonnell) [reply vault/resource_jwt_auth_backend_test.go]: Done!

**Comment by sam-allen-skyspecs** [comment]
Hooray!

**Comment by jasonodonnell** [comment]
When fixing this bug I introduced an upgrade error. We're looking into solutions internally but this bug was disclosed here #1112 and a small workaround provided if this is blocking you. Sorry for the inconvenience!
