### PR TITLE
Fix nil pointer during duplicate group name creation

### LINKED ISSUE #1351: crash when changing case of vault_identity_group name
### Terraform Version
```
Terraform v1.1.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.1.0
+ provider registry.terraform.io/hashicorp/azuread v2.5.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/vault v3.2.1
+ provider registry.terraform.io/scottwinkler/shell v1.7.10
```

### Affected Resource(s)
Please list the resources as a list, for example:
- vault_identity_group
- vault_identity_group_alias

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
locals {
  vault_assignments = {
    engineering = [
    #Engineering = [
      "default",
    ]
  }
}

data "azuread_groups" "azure" {
   display_name = keys(local.vault_assignments)
}

resource "vault_identity_group" "azure" {
  for_each = local.vault_assignments
  name     = each.key
  type     = "external"
  policies = each.value
 }
resource "vault_identity_group_alias" "azure" {
  for_each       = local.vault_assignments
  name           = data.azruead_groups[each.key].id
  mount_accessor = vault_jwt_auth_backend.azure.accessor
  canonical_id   = vault_identity_group.azure[each.key].id
}
```

### Debug Output
No debugging output was generated.

### Panic Output

```
Stack trace from the terraform-provider-vault_v3.2.1_x4 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x1059dbc54]

goroutine 132 [running]:
github.com/hashicorp/terraform-provider-vault/vault.identityGroupCreate(0x14000adf000, {0x105ec7b60, 0x140002dba40})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vault/vault/resource_identity_group.go:189 +0x434
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1400054b6c0, {0x105f06be8, 0x14000595600}, 0x14000adf000, {0x105ec7b60, 0x140002dba40})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/resource.go:329 +0x170
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1400054b6c0, {0x105f06be8, 0x14000595600}, 0x140005e1930, 0x14000adee80, {0x105ec7b60, 0x140002dba40})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/resource.go:467 +0x8d8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14000284528, {0x105f06be8, 0x14000595600}, 0x14000aaa8c0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/grpc_provider.go:977 +0xe38
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x1400013aa80, {0x105f06c90, 0x140005edcb0}, 0x140001a2ee0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x338
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x105e915c0, 0x1400013aa80}, {0x105f06c90, 0x140005edcb0}, 0x1400088d0e0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x140005048c0, {0x105f1b580, 0x1400075c000}, 0x14000a605a0, 0x140004c7c50, 0x1066a0da0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:1279 +0xc60
google.golang.org/grpc.(*Server).handleStream(0x140005048c0, {0x105f1b580, 0x1400075c000}, 0x14000a605a0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:1608 +0xa34
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x1400003ee40, 0x140005048c0, {0x105f1b580, 0x1400075c000}, 0x14000a605a0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:923 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:921 +0x1f0

Error: The terraform-provider-vault_v3.2.1_x4 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

Ideally, handled gracefully or rejected the change because of duplicate values (I know Vault lower-cases things internally).

### Actual Behavior
Crashed

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. change the case of the identity group name
2. `terraform apply`

### Important Factoids
None

### References
None

### PR DESCRIPTION
**Pull request by benashz**
This PR fixes a nil pointer whenever a duplicate identity group is being created within the same apply operation.

Fixes:
- don't blow up when constructing the error message
- provide a more meaningful error message
- document usage patterns that should be avoided for identity groups

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #1351 

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vault/blob/master/CHANGELOG.md):

```release-note

```

Output from acceptance testing:

```
$ make testacc TESTARGS='-v -test.run TestAccIdentityGroup'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test -v -v -test.run TestAccIdentityGroup -timeout 30m ./...

[...]

ok      github.com/hashicorp/terraform-provider-vault/util      (cached) [no tests to run]
=== RUN   TestAccIdentityGroupAlias
--- PASS: TestAccIdentityGroupAlias (1.83s)
=== RUN   TestAccIdentityGroupAliasUpdate
--- PASS: TestAccIdentityGroupAliasUpdate (3.20s)
=== RUN   TestAccIdentityGroupMemberEntityIdsExclusiveEmpty
--- PASS: TestAccIdentityGroupMemberEntityIdsExclusiveEmpty (4.38s)
=== RUN   TestAccIdentityGroupMemberEntityIdsExclusive
    resource_identity_group_member_entity_ids_test.go:53: &{{{{0 0} 0 0 0 0} [] {0xc000a32b60} false false false false map[] map[] []  [] false 0xc000cb2420 false 0 0 testing.tRunner 0xc000682820 1 [17887630 17877282 17887295 17882525 30629611 17013223 17214849] TestAccIdentityGroupMemberEntityIdsExclusive {13869986855062114408 9425681177 0x2d1cce0} 0 0xc000355800 0xc00010e380 [] {0 0}  <nil> 0} false false 0xc0000f7950}
--- SKIP: TestAccIdentityGroupMemberEntityIdsExclusive (0.00s)
=== RUN   TestAccIdentityGroupMemberEntityIdsNonExclusiveEmpty
--- PASS: TestAccIdentityGroupMemberEntityIdsNonExclusiveEmpty (4.49s)
=== RUN   TestAccIdentityGroupMemberEntityIdsNonExclusive
    resource_identity_group_member_entity_ids_test.go:123: &{{{{0 0} 0 0 0 0} [] {0xc000a32340} false false false false map[] map[] []  [] false 0xc000cb2420 false 0 0 testing.tRunner 0xc000682820 1 [17887630 17877282 17887295 17882525 30629611 17013223 17214849] TestAccIdentityGroupMemberEntityIdsNonExclusive {13869986859922917528 13917651242 0x2d1cce0} 0 0xc000354f60 0xc0011c80e0 [] {0 0}  <nil> 0} false false 0xc0000f7950}
--- SKIP: TestAccIdentityGroupMemberEntityIdsNonExclusive (0.00s)
=== RUN   TestAccIdentityGroupPoliciesExclusive
--- PASS: TestAccIdentityGroupPoliciesExclusive (3.02s)
=== RUN   TestAccIdentityGroupPoliciesNonExclusive
--- PASS: TestAccIdentityGroupPoliciesNonExclusive (3.09s)
=== RUN   TestAccIdentityGroup
--- PASS: TestAccIdentityGroup (1.68s)
=== RUN   TestAccIdentityGroupUpdate
--- PASS: TestAccIdentityGroupUpdate (7.07s)
=== RUN   TestAccIdentityGroupExternal
--- PASS: TestAccIdentityGroupExternal (1.67s)
=== RUN   TestAccIdentityGroup_DuplicateCreate
--- PASS: TestAccIdentityGroup_DuplicateCreate (0.97s)
PASS
ok      github.com/hashicorp/terraform-provider-vault/vault     32.025s


...
```

### CODE REVIEW

File: vault/resource_identity_group.go [hunk 1]
```diff
@@ -183,17 +184,18 @@ func identityGroupCreate(d *schema.ResourceData, meta interface{}) error {
...
+			if resp != nil {
+				err = fmt.Errorf(
+					"group already exists with path=%q, id=%q", path, resp.Data["id"])
+			}
 		}
-
-		return fmt.Errorf("Identity Group %q already exists. %s", name, groupMsg)
-	} else {
-		log.Printf("[DEBUG] Wrote IdentityGroup %q", resp.Data["name"])
+		return fmt.Errorf("failed to create identity group %q, reason=%w", name, err)
```
Comment (vinay-gopalan) [inline vault/resource_identity_group.go:195]: nit: any reason we are using `reason=%w` as opposed to `err=%w` like we are doing in other places in the code?

Comment (benashz) [reply vault/resource_identity_group.go:195]: Good question, it's largely due to the fact that `reason` may not have been derived from an actual `error`. For example when both `resp` and  `err` are nil. I am  happy to go with the other pattern as well.

Comment (vinay-gopalan) [reply vault/resource_identity_group.go:195]: Got it, that makes sense

**Review by vinay-gopalan — APPROVED** [review]
LGTM!
