### PR TITLE
Resolve TF state for PKI Multi-Issuer workflows

### LINKED ISSUE #1943: `key_name` parameter ignored in `vault_pki_secret_backend_intermediate_cert_request` resource creation
### Terraform Version

Terraform v1.5.3 on linux_amd64
Vault v1.14.0 (13a649f860186dffe3f3a4459814d87191efc321), built 2023-06-19T11:40:23Z

### Affected Resource(s)
- vault_pki_secret_backend_intermediate_cert_request

### Terraform Configuration Files
```hcl
resource "vault_mount" "pki_int" {
  path                  = "pki_int"
  type                  = "pki"
  description           = "PKI engine hosting intermediate CA"
  max_lease_ttl_seconds = 157680000
}

resource "vault_pki_secret_backend_intermediate_cert_request" "csr" {
  backend      = vault_mount.pki_int.path
  type         = "internal"
  organization = "Example"
  common_name  = "Example Intermediate CA"
  key_type     = "ec"
  key_bits     = 256
  key_name     = "my_key"
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
The generated private key should be named `my_key`.

### Actual Behavior
The generated private key has no name.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`
3. `vault list -detailed pki_int/keys`
```
Keys                                    is_default    key_name
----                                    ----------    --------
b3d64a33-6e49-ae16-43de-dc62981a1680    true          n/a
```

### Important Factoids
N/A

### References
N/A

### PR DESCRIPTION
**Pull request by vinay-gopalan**
This PR aims to address/fix the following issues:

- Some Key Fields (`key_name`, `key_ref`) not being written to Vault due to inaccurate conditionals.
- Nil check on Issuer Read that was causing a panic when reading from a fresh Vault server
- Root certs were being destroyed and recreated due to the `CustomizeDiff` function not accounting for multi-issuer support. Previously, we were comparing the serials for all root certs to the `default` issuer's PEM certificate. The function has now been updated to read the PEM certificate for a specific issuer with an `issuer_id` and compare with the correct serial
- Ensures all root cert and intermediate cert resources have unique IDs since there can now be multiple resources for each type.

Fixes #1943 #1944 #1968 

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vault/blob/master/CHANGELOG.md):

```release-note
Resolve the TF state for PKI Multi-Issuer workflows.
```

### CODE REVIEW

File: vault/resource_pki_secret_backend_intermediate_cert_request.go [hunk 1]
```diff
@@ -262,15 +265,19 @@ func pkiSecretBackendIntermediateCertRequestCreate(ctx context.Context, d *schem
 
 	// add multi-issuer write API fields if supported
 	isIssuerAPISupported := provider.IsAPISupported(meta, provider.VaultVersion111)
+	isKeyBeingGenerated := !(intermediateType == keyTypeKMS || intermediateType == consts.FieldExisting)
```
Comment (stevendpclark) [inline vault/resource_pki_secret_backend_intermediate_cert_request.go:268]: Sorry @vinay-gopalan, I thought about this last night and this is slightly incorrect. 

The `kms` exported type technically creates a key within PKI (just not key material, that is stored in the HSM).  So we need to guard `consts.FieldKeyType` and `consts.FieldKeyBits` against being used for `kms` and `existing` types but `consts.FieldKeyName` should be available to the `kms` type...

File: vault/resource_pki_secret_backend_intermediate_cert_request.go [hunk 2]
```diff
@@ -262,15 +265,19 @@ func pkiSecretBackendIntermediateCertRequestCreate(ctx context.Context, d *schem
...
+			intermediateCertAPIFields = append(intermediateCertAPIFields, consts.FieldKeyName)
 		}
-	} else if isIssuerAPISupported {
-		intermediateCertAPIFields = append(intermediateCertAPIFields, consts.FieldKeyName)
+	} else {
+		intermediateCertAPIFields = append(intermediateCertAPIFields, consts.FieldKeyRef)
+	}
+
+	if isIssuerAPISupported {
+		intermediateCertAPIFields = append(intermediateCertAPIFields, consts.FieldIssuerName)
```
Comment (stevendpclark) [inline vault/resource_pki_secret_backend_intermediate_cert_request.go:280]: Also incorrect copy/paste on my part, `issuer_name` is not supported in CSR generation APIs as no issuer is being persisted/created. Keys are though...

File: vault/resource_pki_secret_backend_root_cert.go [hunk 3]
```diff
@@ -53,9 +57,38 @@ func pkiSecretBackendRootCertResource() *schema.Resource {
 				return e
 			}
 
-			cert, err := getCACertificate(client, d.Get(consts.FieldBackend).(string))
-			if err != nil {
-				return err
+			var cert *x509.Certificate
+			isIssuerAPISupported := provider.IsAPISupported(meta, provider.VaultVersion111)
```
Comment (vinay-gopalan) [inline vault/resource_pki_secret_backend_root_cert.go:61]: Prior to multi-issuer support (<= Vault 1.10), this customize diff would read the default CA in PEM format and compare to what was in the TF state. When there is only one issuer, this makes sense since it will be the default. However, for multiple issuers, all Root Cert resources that are not the default issuer will be forced to be recreated. This was leading users into a constant create-destroy cycle when multiple root certs were added in a TF file.

This update now correctly read the specific issuer's certificate in PEM format, and compare to what is in the TF state. If there is a change in the certificate, the Root Cert is recreated. Also, if an issuer is deleted outside of TF, this update correctly resolves the state by recreating the resource.

File: vault/resource_pki_secret_backend_intermediate_cert_request.go (hunk 1 above)
Comment (vinay-gopalan) [reply vault/resource_pki_secret_backend_intermediate_cert_request.go]: Thanks @stevendpclark! I made the necessary updates and also added some better test coverage for the root and intermediate cert resources.

File: vault/resource_pki_secret_backend_intermediate_cert_request.go (hunk 2 above)
Comment (vinay-gopalan) [reply vault/resource_pki_secret_backend_intermediate_cert_request.go]: Updated in latest :)

**Review by raymonstah — APPROVED** [review]
🎉

File: vault/resource_pki_secret_backend_root_cert.go [hunk 4]
```diff
@@ -53,9 +57,38 @@ func pkiSecretBackendRootCertResource() *schema.Resource {
...
+			if isIssuerAPISupported {
+				// get the specific certificate for issuer with issuer_id
+				cert, e = getIssuerPEM(client, d.Get(consts.FieldBackend).(string), d.Get(consts.FieldIssuerID).(string))
+				if e != nil {
+					// Check if this is an out-of-band change on the issuer
+					if util.Is500(e) && util.ErrorContainsString(e, issuerNotFoundErr) {
+						log.Printf("issuer deleted out-of-band. re-creating root cert")
```
Comment (fairclothjm) [inline vault/resource_pki_secret_backend_root_cert.go:68]: Should there be a level associated with this log?

**Review by fairclothjm — APPROVED** [review]

File: util/util.go [hunk 5]
```diff
@@ -64,6 +68,14 @@ func ErrorContainsHTTPCode(err error, codes ...int) bool {
 	return false
 }
 
+func ErrorContainsString(err error, s string) bool {
+	if strings.Contains(err.Error(), s) {
+		return true
+	}
+
+	return false
```
[the remark this answers is not in the document]
Comment (vinay-gopalan) [reply util/util.go]: Good catch!

File: vault/resource_pki_secret_backend_root_cert.go (hunk 4 above)
Comment (vinay-gopalan) [reply vault/resource_pki_secret_backend_root_cert.go]: Added a `WARN` level, thanks for the catch!
