### PR TITLE
auth/aws: Enhance AWS authentication with role assumption and custom endpoints.

### LINKED ISSUE #1808: auth_login_aws should always try to assume role if aws_role_arn  value is provided
### Terraform Version
Terraform version: 1.4.2

### Affected Resource(s)
- provider

### Terraform Configuration Files
```hcl
provider "vault" {
  address = "https://vault.company.com/"
  auth_login_aws {
    role         = "admin"
    aws_region   = "eu-central-1"
    aws_role_arn = "arn:aws:iam::44455xxxx552:role/my-role"
  }
}
```

### Debug Output
After some debugging I find out that go-secure-stdlib is used to create aws session. This lib only support assuming role if web identity token is provided 
image
I think vault provider should not ignore aws_role_arn if web identity token is not provider and should try to assume role with aws_access_key keys or profile.

### Panic Output
n/a

### Expected Behavior
Vault provider should assume aws role before trying to connect to vault.

### Actual Behavior
Role is ignored and default profile credentials used.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
n/a

### References
n/a

### PR DESCRIPTION
**Pull request by Balaji2198**
### Description

- Refactor `getLoginData` to support role assumption using STS.
- Introduce custom endpoint resolvers for STS and IAM services.
- Update `getCredentialsConfig` to utilize new options for role ARN and session name.
- Implement `generateLoginData` to create presigned requests for AWS API calls.
- Add unit tests for role assumption logic, session token handling, and custom endpoint configuration.
- Migrate to `awsutil/v2` for improved credential management.

Relates OR Closes #1808

### Checklist
- [x] Added [CHANGELOG](https://github.com/hashicorp/terraform-provider-vault/blob/master/CHANGELOG.md) entry (only for user-facing changes)
- [x] Acceptance tests where run against all supported Vault Versions

### Output from acceptance testing:

```
$ make testacc TESTARGS='--run=TestAuthLoginAWS_*'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test --run=TestAuthLoginAWS_* -timeout 30m ./...
?       github.com/hashicorp/terraform-provider-vault   [no test files]
?       github.com/hashicorp/terraform-provider-vault/acctestutil       [no test files]
?       github.com/hashicorp/terraform-provider-vault/cmd/coverage      [no test files]
?       github.com/hashicorp/terraform-provider-vault/cmd/generate      [no test files]
ok      github.com/hashicorp/terraform-provider-vault/codegen   0.527s [no tests to run]
?       github.com/hashicorp/terraform-provider-vault/helper    [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/consts   [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/framework/base   [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/framework/client [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/framework/errutil        [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/framework/model  [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/framework/token  [no test files]
ok      github.com/hashicorp/terraform-provider-vault/internal/framework/validators     1.079s [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/internal/identity/entity  0.965s [no tests to run]
?       github.com/hashicorp/terraform-provider-vault/internal/identity/group   [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/identity/mfa     [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/pki      [no test files]
ok      github.com/hashicorp/terraform-provider-vault/internal/provider 1.649s
?       github.com/hashicorp/terraform-provider-vault/internal/provider/fwprovider      [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/providertest     [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/rotation [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/sync     [no test files]
ok      github.com/hashicorp/terraform-provider-vault/internal/vault/auth/spiffe        1.676s [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/internal/vault/secrets/azure      2.261s [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/internal/vault/secrets/ephemeral  2.518s [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/internal/vault/sys        3.584s [no tests to run]
?       github.com/hashicorp/terraform-provider-vault/schema    [no test files]
ok      github.com/hashicorp/terraform-provider-vault/testutil  2.422s [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/util      2.798s [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/util/mountutil    3.139s [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/vault     3.370s [no tests to run]
...
```

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

## PCI review checklist

- [ ] I have documented a clear reason for, and description of, the change I am making.

- [ ] If applicable, I've documented a plan to revert these changes if they require more than reverting the pull request.

- [ ] If applicable, I've documented the impact of any changes to security controls.

  Examples of changes to security controls include using new access control methods, adding or removing logging pipelines, etc.

### CODE REVIEW

**Review by vijayavelsekar — COMMENTED** [review]
Looks good to me

File: internal/provider/auth_aws.go [hunk 1]
```diff
@@ -247,71 +259,238 @@ func (l *AuthLoginAWS) getDefaults() authDefaults {
...
+
+	// Force credential retrieval to ensure any AssumeRole calls happen before presigning
+	// This is critical when role assumption is configured
+	tempCreds, err := awsConfig.Credentials.Retrieve(ctx)
+	if err != nil {
+		return nil, fmt.Errorf("failed to retrieve AWS credentials: %w", err)
+	}
+
+	// Check if credentials are actually populated
+	if tempCreds.AccessKeyID == "" {
```
Comment (vijayavelsekar) [inline internal/provider/auth_aws.go]: Do you think we can replace this check with below would make it more defensive ?
`if tempCreds.AccessKeyID == "" || tempCreds.SecretAccessKey == ""`

File: internal/provider/auth_aws.go [hunk 2]
```diff
@@ -247,71 +259,238 @@ func (l *AuthLoginAWS) getDefaults() authDefaults {
...
+// generateLoginData generates the necessary login data for Vault AWS authentication
+// by creating a presigned STS GetCallerIdentity request.
+func generateLoginData(ctx context.Context, awsConfig *aws.Config, headerValue string, logger hclog.Logger) (map[string]interface{}, error) {
+	const iamServerIdHeader = "X-Vault-AWS-IAM-Server-ID"
+
+	loginData := make(map[string]interface{})
+
+	// Force credential retrieval to ensure any AssumeRole calls happen before presigning
+	// This is critical when role assumption is configured
+	tempCreds, err := awsConfig.Credentials.Retrieve(ctx)
```
Comment (vijayavelsekar) [inline internal/provider/auth_aws.go]: Why do we need to Retrieve another tempCreds? We have already generated an assumed Creds in getLoginData function that is wrapped inside awsConfig right ?  I'm proposing below code. Let me know if I'm missing something here (I might be wrong).
```
if headerValue != "" {
		awsConfig.APIOptions = append(awsConfig.APIOptions, func(stack *middleware.Stack) error {
			return stack.Build.Add(middleware.BuildMiddlewareFunc(
				"AddVaultHeader",
				func(ctx context.Context, in middleware.BuildInput, next middleware.BuildHandler) (middleware.BuildOutput, middleware.Metadata, error) {
					req, ok := in.Request.(*smithyhttp.Request)
					if ok {
						req.Header.Add(iamServerIdHeader, headerValue)
					}
					return next.HandleBuild(ctx, in)
				},
			), middleware.After)
		})
	}

	// Create STS client directly with awsConfig
	stsClient := sts.NewFromConfig(*awsConfig)
```

Comment (Balaji2198) [reply internal/provider/auth_aws.go]: Good catch! We can skip the `tempCreds` handling and just rely on `awsConfig` when creating the STS client. I’d still keep the explicit `Credentials.Retrieve` call though, since the AWS SDK loads credentials lazily, this retrieval helps surface any misconfigurations or errors up front.

File: CHANGELOG.md [hunk 3]
```diff
@@ -21,9 +21,15 @@ FEATURES:
 IMPROVEMENTS:
 * Added fields related to namespace used to create a role in kubernetes auth method: ([#2644](https://github.com/hashicorp/terraform-provider-vault/pull/2644))
 
+IMPROVEMENTS:
```
Comment (vijayavelsekar) [inline CHANGELOG.md]: Duplicate IMPROVEMENTS headline.

**Review by fairclothjm — APPROVED** [review]
