### PR TITLE
Avoid writing empty strings to Vault when creating managed keys

### LINKED ISSUE #1772: Unable to create a PKCS#11 `vault_managed_key`
Hi there,

we're trying to use the Vault provider to configure a Vault cluster with PKI capability, and one of the things we need to provision is the managed key in the HSM. The resource for that, `vault_managed_keys` seems to only be tested for hyperscalers, not for PKCS#11, and is failing. The documentation for the Vault API `sys/managed-keys` states that `slot or token label required`, but the Terraform provider is always sending a token label, even if none is specified in the resource.

### Terraform Version
Vault 1.12.3+ent.hsm

### Affected Resource(s)
- vault_managed_key

### Terraform Configuration Files
```hcl
resource "vault_managed_keys" "hsm_pki_managed_key" {
  pkcs {
    name               = "myhsm"
    library            = "myhsm"
    key_label          = "kms-intermediate"
    key_id             = "kms-intermediate"
    key_bits           = "4096"
    slot               = "586615635"
    pin                = "1234"
    mechanism          = "0x000d"
    allow_store_key    = true
    allow_generate_key = true
    any_mount          = false
  }
}
```

### Debug Output
The key part of the log output shows that the data blob POSTed to Vault includes `"token_label": ""`, however this should be ommited if `slot` is present.

https://gist.github.com/Cylindric/521b79028ebe1ec4f9e813eaab1bfe79

### Expected Behavior
A new managed key should be created with the specified settings.

### Actual Behavior
The `terraform apply` fails with an Internal Server Error from the vault server, complaining that:
> both a token lable and a slot cannot be provided

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
This is currently running against a local SoftHSM test environment, but I'm pretty sure this is a discrepancy between the Provider and the Vault API, and not the HSM itself. The equivalent CLI command (that does work) is this:
```bash
vault write sys/managed-keys/pkcs11/myhsm \
      library=myhsm \
      slot=3452623623 \
      pin=1234 \
      key_label=myhsm \
      allow_store_key=true \
      allow_generate_key=true \
      mechanism=0x000d \
      key_bits=4096 \
      any_mount=false
```

### References
[Vault Provider Reference](https://registry.terraform.io/providers/hashicorp/vault/latest/docs)
[Vault Managed-Keys API Doc](https://developer.hashicorp.com/vault/api-docs/system/managed-keys)
[Vault Provider possible code location](https://github.com/hashicorp/terraform-provider-vault/blob/04819e341801f5270b7aebab78c25bc17116eef5/vault/resource_managed_keys.go#L458)

### PR DESCRIPTION
**Pull request by vinay-gopalan**
This PR adds a fix where empty strings were being written to Vault. We should make it so that only fields provided by the user are written along with the data to Vault; if a field is not provided, empty string values should not be written. This was causing PKCS key creation to fail, since two mutually exclusive fields `slot` and `token_label` were both being sent to Vault. The PR also adds a test that is meant to be run locally since it requires a lot of prior setup (including its own Vault server config)

Fixes #1772 

Output from acceptance testing:
```
=== RUN   TestManagedKeysPKCS
--- PASS: TestManagedKeysPKCS (1.69s)
PASS
```

### CODE REVIEW

**Review by raymonstah — APPROVED** [review]

File: vault/resource_managed_keys_test.go [hunk 1]
```diff
@@ -158,6 +158,53 @@ func TestManagedKeys(t *testing.T) {
 	})
 }
 
+// The following test requires a Vault server to be set up with a specific server configuration
```
Comment (fairclothjm) [inline vault/resource_managed_keys_test.go:161]: Are these steps documented somewhere? I am not confident I could get this test running by following this comment alone.

Comment (vinay-gopalan) [reply vault/resource_managed_keys_test.go:161]: Good call, I can document the steps to create a PKCS#11 key and share it to our Google Drive folder or Confluence

Comment (fairclothjm) [reply vault/resource_managed_keys_test.go:161]: Thanks! I made a note to discuss in our dev sync. But I think we should make sure any local only test setups are well documented. I think creating a Confluence page to document these is a good idea!
