### PR TITLE
Fix construction of metadata path in KV V2 resource

### LINKED ISSUE #1719: bug: metadata functionality has broken kv_secret_v2 resource
Noticing an issue with the kv_secret_v2 resource where API calls to Vault are being mangled due to the recently added metadata functionality.

### Versions

- Terraform: 1.3.1
- Provider: [v3.12.0](https://github.com/hashicorp/terraform-provider-vault/releases/tag/v3.12.0)

### Affected Resource(s)

- kv_secret_v2

### Terraform Configuration Files
```hcl
resource "vault_kv_secret_v2" "workspace_id" {
  for_each = local.workspace_ids
  provider = vault.infra-prod
  mount    = "cloud-metadata"
  name     = "aws/account/${each.key}/bootstrap-workspace-id"

  data_json = jsonencode({
    value       = each.value
    description = "TRUNCATED"
    }
  )
}
```

### Debug Output

I don't have the debug output handy, but this should be sufficient as well as the below explanation:

```
Error: Error making API request. URL: GET https://vault.truncated.com/v1/cloud-metametadata/data/aws/account/TRUNCATED/bootstrap-workspace-id Code: 403. Errors: * 1 error occurred: * permission denied
with vault_kv_secret_v2.workspace_id["TRUNCATED"]
on vault.tf line 1, in resource "vault_kv_secret_v2" "workspace_id":
resource "vault_kv_secret_v2" "workspace_id" {
```

### Expected Behavior

Resource to write/update the values correctly. This used to work, and the only change is the provider version.

### Actual Behavior

It looks as though the API url that is getting generated has been mangled and is not correctly using the values that we have input.

### Steps to Reproduce

Use a secret engine or secret path that includes the word `data`.

### Important Factoids

It looks as though this bug was introduced in [PR #1687](https://github.com/hashicorp/terraform-provider-vault/pull/1687) (see [this line](https://github.com/hashicorp/terraform-provider-vault/pull/1687/files#diff-5135769a1d9af820dbf7d72c9c043ff5d19b2969a77354a0ef5a51efa109b2acR278)), where the provider attempts to generate the metadata URL by simply doing a string replacement of the data-path that was generated for reads. The problem with this is that the path can contain "data" (or "/data", "data/", whichever it's matching), and this is what looks to mangle the generated URL.

The above logic should be changed to explicitly generate the metadata URL rather than relying on the previously generated one (for data).

### References

- [PR 1687](https://github.com/hashicorp/terraform-provider-vault/pull/1687)

### PR DESCRIPTION
**Pull request by vinay-gopalan**
In v3.12.0 we enabled support for [adding metadata to KV V2 secrets](#1687). This introduced a regression due to incorrect construction of the metadata path while reading metadata from Vault. This PR fixes the construction of the metadata path, and also ensures that the fields `name` and `mount` are now being set on imports. The PR also adds an updated test to cover the use-cases that would reproduce this bug.

Fixes #1719 

```
=== RUN   TestAccKVSecretV2
--- PASS: TestAccKVSecretV2 (4.73s)
PASS
```

### CODE REVIEW

File: vault/resource_kv_secret_v2.go [hunk 1]
```diff
@@ -217,12 +217,33 @@ func kvSecretV2Read(_ context.Context, d *schema.ResourceData, meta interface{})
...
+	if path == "" {
+		return nil
+	}
 
 	if err := d.Set(consts.FieldPath, path); err != nil {
 		return diag.FromErr(err)
 	}
 
 	if shouldRead {
+		parsedPath := strings.Split(path, "/")
```
Comment (benashz) [inline vault/resource_kv_secret_v2.go:229]: Seems good, but shouldn't we always be setting some values e.g. `mount`, `metadata`, etc... ?

You may want to limit the number of substrings to 3, using `strings.SplitN()` instead of `strings.Split()`,  I am not sure if the `name` component is allowed to contain `/`'s.

File: vault/resource_kv_secret_v2_test.go [hunk 2]
```diff
@@ -56,8 +59,28 @@ func TestAccKVSecretV2(t *testing.T) {
...
+					resource.TestCheckResourceAttr(resourceName, "data.flag", "false"),
+				),
+			},
+			{
+				ResourceName:      resourceName,
+				ImportState:       true,
+				ImportStateVerify: true,
+				ImportStateVerifyIgnore: []string{
+					"data_json", "disable_read",
+					"delete_all_versions", "cas",
```
Comment (benashz) [inline vault/resource_kv_secret_v2_test.go:83]: are we sure none of these fields can be imported?

File: vault/resource_kv_secret_v2_test.go [hunk 3]
```diff
@@ -16,6 +16,9 @@ func TestAccKVSecretV2(t *testing.T) {
 	mount := acctest.RandomWithPrefix("tf-kvv2")
 	name := acctest.RandomWithPrefix("tf-secret")
 
+	updatedMount := acctest.RandomWithPrefix("tf-cloud-metadata")
+	updatedName := acctest.RandomWithPrefix("tf-database-creds")
+
```
Comment (benashz) [inline vault/resource_kv_secret_v2_test.go:21]: Should we also be asserting something about `metadata` in the first step below?, or perhaps in all `TestStep`s?

**Review by benashz — COMMENTED** [review]
Seems good. I had a few questions/suggestions that probably need to be looked at.

File: vault/resource_kv_secret_v2.go (hunk 1 above)
Comment (vinay-gopalan) [reply vault/resource_kv_secret_v2.go]: Good call! I noticed another test was failing because that test dealt with nested secrets (`name` dod contain `/`'s in that case), and using `SplitN` instead to limit the substrings fixes that. Thanks for the callout!

I also updated the code to always set all the fields that can be set without reading the secret itself (in case of `disable_read`, we won't detect the drift on any fields that are dependent on the secret being read)

File: vault/resource_kv_secret_v2_test.go (hunk 2 above)
Comment (vinay-gopalan) [reply vault/resource_kv_secret_v2_test.go]: Just double-checked. Looks like `cas` can be imported! Rest remain in the Verify Ignore list

**Review by fairclothjm — APPROVED** [review]

File: vault/resource_kv_secret_v2_test.go (hunk 3 above)
Comment (vinay-gopalan) [reply vault/resource_kv_secret_v2_test.go:24]: Sorry for the delay on this! Added some checks to test `metadata` in the test steps

File: vault/resource_kv_secret_v2.go [hunk 4]
```diff
@@ -220,12 +220,33 @@ func kvSecretV2Read(_ context.Context, d *schema.ResourceData, meta interface{})
...
 		return diag.FromErr(err)
 	}
 
+	// id should be of the form "mount/data/name"
+	// limit substrings to 3 in case name has '/'
+	// in it or if it's a nested secret
+	parsedPath := strings.SplitN(path, "/", 3)
+
+	mount := parsedPath[0]
+	name := parsedPath[2]
```
Comment (fairclothjm) [inline vault/resource_kv_secret_v2.go:237]: Should we be checking the length of `parsedPath` before accessing an index? Or can we safely assume that it has a length of 3 here?

Comment (vinay-gopalan) [reply vault/resource_kv_secret_v2.go:240]: Good call! The length should be 3 based on how we're constructing it within the `Write` method, but added an assertion check just to be sure 😄

**Review by fairclothjm — APPROVED** [review]
