### PR TITLE
merge JWT tune block fields using user provided values and tune API response

### LINKED ISSUE #2234: [Bug]: vault_jwt_auth_backend tune block always updates unless config matches Vault server defaults
### Terraform Core Version

1.7.5

### Terraform Vault Provider Version

4.2.0

### Vault Server Version

1.15.7+ent

### Affected Resource(s)

- vault_jwt_auth_backend

### Expected Behavior

There should be no changes reported by Terraform if the configured `tune` block parameters have not changed.

### Actual Behavior

Terraform always reports that the `vault_jwt_auth_backend` resource will be updated in-place unless all of the tune parameters (`default_lease_ttl`, `max_lease_ttl`, and `token_type` are currently the only ones with default values) match the defaults (I'm assuming as reported by the target Vault server, rather than defaults set within the provider code). This includes when the `tune` block exists but has no attributes configured (as none of the attributes are required).

### Relevant Error/Panic Output Snippet

```shell
$ terraform apply -auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # vault_jwt_auth_backend.jwt_backend will be created
  + resource "vault_jwt_auth_backend" "jwt_backend" {
      + accessor           = (known after apply)
      + bound_issuer       = "https://token.actions.githubusercontent.com"
      + disable_remount    = false
      + id                 = (known after apply)
      + local              = false
      + namespace_in_state = true
      + oidc_discovery_url = "https://token.actions.githubusercontent.com"
      + path               = "jwt-test"
      + tune               = [
          + {
              + allowed_response_headers     = []
              + audit_non_hmac_request_keys  = []
              + audit_non_hmac_response_keys = []
              + default_lease_ttl            = ""
              + listing_visibility           = ""
              + max_lease_ttl                = ""
              + passthrough_request_headers  = []
              + token_type                   = "default-service"
            },
        ]
      + type               = "jwt"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
vault_jwt_auth_backend.jwt_backend: Creating...
vault_jwt_auth_backend.jwt_backend: Creation complete after 1s [id=jwt-test]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

$ terraform apply -auto-approve
vault_jwt_auth_backend.jwt_backend: Refreshing state... [id=jwt-test]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # vault_jwt_auth_backend.jwt_backend will be updated in-place
  ~ resource "vault_jwt_auth_backend" "jwt_backend" {
        id                     = "jwt-test"
      ~ tune                   = [
          - {
              - allowed_response_headers     = []
              - audit_non_hmac_request_keys  = []
              - audit_non_hmac_response_keys = []
              - default_lease_ttl            = "768h"
              - listing_visibility           = ""
              - max_lease_ttl                = "768h"
              - passthrough_request_headers  = []
              - token_type                   = "default-service"
            },
          + {
              + allowed_response_headers     = []
              + audit_non_hmac_request_keys  = []
              + audit_non_hmac_response_keys = []
              + default_lease_ttl            = ""
              + listing_visibility           = ""
              + max_lease_ttl                = ""
              + passthrough_request_headers  = []
              + token_type                   = "default-service"
            },
        ]
        # (12 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
vault_jwt_auth_backend.jwt_backend: Modifying... [id=jwt-test]
vault_jwt_auth_backend.jwt_backend: Modifications complete after 0s [id=jwt-test]
```

### Terraform Configuration Files

Sample configuration that always produces an update in-place operation:
```hcl
terraform {
  required_providers {
    vault = {
      source  = "hashicorp/vault"
      version = "= 4.2.0"
    }
  }
  required_version = ">= 1.7.0"
}

resource "vault_jwt_auth_backend" "jwt_backend" {
  path = "jwt-test"
  type = "jwt"

  bound_issuer       = "https://token.actions.githubusercontent.com"
  oidc_discovery_url = "https://token.actions.githubusercontent.com"

  tune {
    token_type = "default-service"  
  }
}
```

Sample configuration that reports "No changes" (I assume the values for `default_lease_ttl`, and `max_lease_ttl` would need to be different if there were different global default values configured for the Vault server):

```hcl
terraform {
  required_providers {
    vault = {
      source  = "hashicorp/vault"
      version = "= 4.2.0"
    }
  }
  required_version = ">= 1.7.0"
}

resource "vault_jwt_auth_backend" "jwt_backend" {
  path = "jwt-test"
  type = "jwt"

  bound_issuer       = "https://token.actions.githubusercontent.com"
  oidc_discovery_url = "https://token.actions.githubusercontent.com"

  tune {
    default_lease_ttl = "768h"
    max_lease_ttl     = "768h"
    token_type        = "default-service"
  }
}
```

### Steps to Reproduce

0. Apply the first Terraform code above to provision the JWT auth backend with `terraform apply`
1. Re-apply the same Terraform code with `terraform apply`
2. Note Terraform reports 1 resource to change when there should be no changes to the infrastructure necessary because the Terraform code has not changed

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

Possibly related to https://github.com/hashicorp/terraform-provider-vault/issues/1172 ? Unclear if the behaviour reported in that issue with the `provider_config` block for OIDC is using the same provider machinery for this issue with the `tune` block.

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by thyton**
### Description

The  PR merges the raw tune GET API response with the user input parsed from the tune schema. Any field with the Vault APIs's global default effect will be set to empty when the user did not provide a value even if the Vault API response returns non-empty. This is to ensure the tune block reflects the user provided values.

Relates OR Closes #2234

### Checklist
- [ ] Added [CHANGELOG](https://github.com/hashicorp/terraform-provider-vault/blob/master/CHANGELOG.md) entry (only for user-facing changes)
- [ ] Acceptance tests where run against all supported Vault Versions

### Output from acceptance testing:

```
$ TF_ACC_ENTERPRISE=1 TF_ACC=1 go test -v ./vault -run TestAccJWTAuthBackend
=== RUN   TestAccJWTAuthBackendRole_import
=== PAUSE TestAccJWTAuthBackendRole_import
=== RUN   TestAccJWTAuthBackendRole_basic
=== PAUSE TestAccJWTAuthBackendRole_basic
=== RUN   TestAccJWTAuthBackendRole_update
=== PAUSE TestAccJWTAuthBackendRole_update
=== RUN   TestAccJWTAuthBackendRole_full
=== PAUSE TestAccJWTAuthBackendRole_full
=== RUN   TestAccJWTAuthBackendRoleOIDC_full
=== PAUSE TestAccJWTAuthBackendRoleOIDC_full
=== RUN   TestAccJWTAuthBackendRoleOIDC_disableParsing
=== PAUSE TestAccJWTAuthBackendRoleOIDC_disableParsing
=== RUN   TestAccJWTAuthBackendRole_fullUpdate
=== PAUSE TestAccJWTAuthBackendRole_fullUpdate
=== RUN   TestAccJWTAuthBackend
=== PAUSE TestAccJWTAuthBackend
=== RUN   TestAccJWTAuthBackendProviderConfig
=== PAUSE TestAccJWTAuthBackendProviderConfig
=== RUN   TestAccJWTAuthBackend_OIDC
=== PAUSE TestAccJWTAuthBackend_OIDC
=== RUN   TestAccJWTAuthBackend_invalid
=== PAUSE TestAccJWTAuthBackend_invalid
=== RUN   TestAccJWTAuthBackend_missingMandatory
=== PAUSE TestAccJWTAuthBackend_missingMandatory
=== RUN   TestAccJWTAuthBackendProviderConfigConversionBool
=== PAUSE TestAccJWTAuthBackendProviderConfigConversionBool
=== RUN   TestAccJWTAuthBackendProviderConfigConversionInt
=== PAUSE TestAccJWTAuthBackendProviderConfigConversionInt
=== RUN   TestAccJWTAuthBackendProviderConfig_negative
    resource_jwt_auth_backend_test.go:608: true
--- SKIP: TestAccJWTAuthBackendProviderConfig_negative (0.00s)
=== RUN   TestAccJWTAuthBackendJWKSPairs_expectedError
--- PASS: TestAccJWTAuthBackendJWKSPairs_expectedError (1.77s)
=== CONT  TestAccJWTAuthBackendRoleOIDC_full
=== CONT  TestAccJWTAuthBackendRole_full
=== CONT  TestAccJWTAuthBackendProviderConfigConversionInt
=== CONT  TestAccJWTAuthBackend_invalid
=== CONT  TestAccJWTAuthBackendProviderConfigConversionBool
--- PASS: TestAccJWTAuthBackendProviderConfigConversionInt (0.00s)
=== CONT  TestAccJWTAuthBackendRole_basic
=== CONT  TestAccJWTAuthBackendRole_import
=== CONT  TestAccJWTAuthBackend_missingMandatory
=== CONT  TestAccJWTAuthBackend
=== RUN   TestAccJWTAuthBackend/basic
=== PAUSE TestAccJWTAuthBackend/basic
=== RUN   TestAccJWTAuthBackend/ns
=== PAUSE TestAccJWTAuthBackend/ns
=== CONT  TestAccJWTAuthBackendRole_update
=== CONT  TestAccJWTAuthBackendRole_fullUpdate
=== CONT  TestAccJWTAuthBackend_OIDC
--- PASS: TestAccJWTAuthBackendProviderConfigConversionBool (0.00s)
=== RUN   TestAccJWTAuthBackend_OIDC/basic
=== PAUSE TestAccJWTAuthBackend_OIDC/basic
=== RUN   TestAccJWTAuthBackend_OIDC/ns
=== PAUSE TestAccJWTAuthBackend_OIDC/ns
=== CONT  TestAccJWTAuthBackendProviderConfig
=== RUN   TestAccJWTAuthBackendProviderConfig/basic
=== PAUSE TestAccJWTAuthBackendProviderConfig/basic
=== RUN   TestAccJWTAuthBackendProviderConfig/ns
=== PAUSE TestAccJWTAuthBackendProviderConfig/ns
=== CONT  TestAccJWTAuthBackendRoleOIDC_disableParsing
=== CONT  TestAccJWTAuthBackend/basic
=== CONT  TestAccJWTAuthBackend/ns
--- PASS: TestAccJWTAuthBackend_invalid (0.63s)
=== CONT  TestAccJWTAuthBackend_OIDC/basic
--- PASS: TestAccJWTAuthBackendRole_basic (1.91s)
--- PASS: TestAccJWTAuthBackendRole_full (2.41s)
=== CONT  TestAccJWTAuthBackendProviderConfig/basic
--- PASS: TestAccJWTAuthBackendRoleOIDC_disableParsing (2.41s)
=== CONT  TestAccJWTAuthBackend_OIDC/ns
--- PASS: TestAccJWTAuthBackendRole_import (2.80s)
=== CONT  TestAccJWTAuthBackendProviderConfig/ns
--- PASS: TestAccJWTAuthBackendRoleOIDC_full (2.97s)
--- PASS: TestAccJWTAuthBackend_missingMandatory (3.28s)
--- PASS: TestAccJWTAuthBackendRole_update (3.51s)
--- PASS: TestAccJWTAuthBackendRole_fullUpdate (4.48s)
--- PASS: TestAccJWTAuthBackend_OIDC (0.00s)
    --- PASS: TestAccJWTAuthBackend_OIDC/basic (2.44s)
    --- PASS: TestAccJWTAuthBackend_OIDC/ns (4.11s)
--- PASS: TestAccJWTAuthBackendProviderConfig (0.00s)
    --- PASS: TestAccJWTAuthBackendProviderConfig/basic (2.36s)
    --- PASS: TestAccJWTAuthBackendProviderConfig/ns (5.00s)
--- PASS: TestAccJWTAuthBackend (0.00s)
    --- PASS: TestAccJWTAuthBackend/basic (7.61s)
    --- PASS: TestAccJWTAuthBackend/ns (9.18s)
PASS
ok      github.com/hashicorp/terraform-provider-vault/vault     12.339s
```

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

## PCI review checklist

- [ ] I have documented a clear reason for, and description of, the change I am making.

- [ ] If applicable, I've documented a plan to revert these changes if they require more than reverting the pull request.

- [ ] If applicable, I've documented the impact of any changes to security controls.

  Examples of changes to security controls include using new access control methods, adding or removing logging pipelines, etc.

### CODE REVIEW

**Review by fairclothjm — DISMISSED** [review]
LGTM!

**Review by fairclothjm — APPROVED** [review]

File: vault/resource_jwt_auth_backend.go [hunk 1]
```diff
@@ -339,7 +339,11 @@ func jwtAuthBackendRead(ctx context.Context, d *schema.ResourceData, meta interf
 	if err != nil {
 		return diag.Errorf("error reading tune information from Vault: %s", err)
 	}
-	if err := d.Set("tune", []map[string]interface{}{rawTune}); err != nil {
+
+	input := expandAuthMethodTune(d.Get("tune").(*schema.Set).List())
```
Comment (benashz) [inline vault/resource_jwt_auth_backend.go:343]: I think we are missing a type assert here. This could result in a panic

**Review by benashz — COMMENTED** [review]
It would be good to fix the possible panic. Otherwise LGTM!
