### PR TITLE
Regression in v5.7.0 when using token on consul secret backend

### LINKED ISSUE #2772: [Bug]: Regression in v5.7.0 when using token on consul secret backend
### Terraform Core Version

0.11.4

### Terraform Vault Provider Version

5.7.0

### Vault Server Version

1.19.5

### Affected Resource(s)

- `vault_consul_secret_backend`

### Expected Behavior

I would like to configure the Consul secret backend like we used to, in a bad way, with a known bootstrap token that isn't rotated.

### Actual Behavior

> Error: field 'bootstrap' must be set to true when neither 'token' nor 'token_wo' is specified

### Relevant Error/Panic Output Snippet

```shell

```

### Terraform Configuration Files

```hcl
resource "random_uuid" "consul_master_token" {}

resource "vault_consul_secret_backend" "this" {
  path        = "consul"
  description = "manages the Consul backend"

  address = "https://consul.service.consul:8501"
  token   = random_uuid.consul_master_token.result
}
```

### Steps to Reproduce

The above snippets are probably enough.

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

I'll try to migrate to `token_wo`, thus far we've got to skip that version.

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by Siddharth-Kannan**
### Description

Fixes a bug in `vault_consul_secret_backend` that incorrectly rejected computed token values (e.g., random_uuid.result). The conditional checks in the `consulSecretsBackendCustomizeDiff` function were incorrectly rejecting computed tokens when the bootstrap field was not present. This change corrects the validation logic to properly handle computed values during the plan phase while still catching all invalid field combinations. Added comprehensive test cases to verify both valid and invalid field configurations.

tested on 1.15.0+ent - 1.21.0+ent

Closes #2772

### Checklist
- [x] Added [CHANGELOG](https://github.com/hashicorp/terraform-provider-vault/blob/master/CHANGELOG.md) entry (only for user-facing changes)
- [x] Acceptance tests where run against all supported Vault Versions

### Output from acceptance testing:

```
# if CONSUL_HTTP_ADDR env is set , "TestConsulSecretBackend_Bootstrap" is skipped.

% go test -v -run TestConsulSecretBackend ./vault -count=1 
=== RUN   TestConsulSecretBackendRole
=== PAUSE TestConsulSecretBackendRole
=== RUN   TestConsulSecretBackendRole_Legacy
    resource_consul_secret_backend_role_test.go:186: Vault server version "1.21.0+ent"
    resource_consul_secret_backend_role_test.go:186: Vault version >= "1.11.0"
--- SKIP: TestConsulSecretBackendRole_Legacy (0.09s)
=== RUN   TestConsulSecretBackendRoleNameFromPath
--- PASS: TestConsulSecretBackendRoleNameFromPath (0.00s)
=== RUN   TestConsulSecretBackendRoleBackendFromPath
--- PASS: TestConsulSecretBackendRoleBackendFromPath (0.00s)
=== RUN   TestConsulSecretBackend
=== PAUSE TestConsulSecretBackend
=== RUN   TestConsulSecretBackend_Bootstrap
=== PAUSE TestConsulSecretBackend_Bootstrap
=== RUN   TestConsulSecretBackend_remount
=== PAUSE TestConsulSecretBackend_remount
=== RUN   TestConsulSecretBackend_WriteOnlyToken
=== PAUSE TestConsulSecretBackend_WriteOnlyToken
=== RUN   TestConsulSecretBackend_WriteOnlyClientKey
=== PAUSE TestConsulSecretBackend_WriteOnlyClientKey
=== RUN   TestConsulSecretBackend_WriteOnlyBoth
=== PAUSE TestConsulSecretBackend_WriteOnlyBoth
=== RUN   TestConsulSecretBackend_LegacyFields
=== PAUSE TestConsulSecretBackend_LegacyFields
=== RUN   TestConsulSecretBackend_WriteOnlyConflicts
=== PAUSE TestConsulSecretBackend_WriteOnlyConflicts
=== RUN   TestConsulSecretBackend_CustomizeDiff
=== PAUSE TestConsulSecretBackend_CustomizeDiff
=== RUN   TestConsulSecretBackend_ComputedTokenWithConsul
=== PAUSE TestConsulSecretBackend_ComputedTokenWithConsul
=== CONT  TestConsulSecretBackendRole
=== CONT  TestConsulSecretBackend_WriteOnlyBoth
=== CONT  TestConsulSecretBackend_remount
=== CONT  TestConsulSecretBackend_Bootstrap
=== CONT  TestConsulSecretBackend
=== CONT  TestConsulSecretBackend_WriteOnlyClientKey
=== CONT  TestConsulSecretBackend_CustomizeDiff
=== CONT  TestConsulSecretBackend_ComputedTokenWithConsul
=== CONT  TestConsulSecretBackend_WriteOnlyConflicts
=== CONT  TestConsulSecretBackend_WriteOnlyToken
=== CONT  TestConsulSecretBackend_LegacyFields
=== NAME  TestConsulSecretBackendRole
    resource_consul_secret_backend_role_test.go:78: Vault server version "1.21.0+ent"
--- PASS: TestConsulSecretBackend_WriteOnlyConflicts (0.72s)
--- PASS: TestConsulSecretBackend_LegacyFields (2.03s)
=== NAME  TestConsulSecretBackend_Bootstrap
    resource_consul_secret_backend_test.go:152: Vault server version "1.21.0+ent"
--- PASS: TestConsulSecretBackend_WriteOnlyClientKey (3.91s)
--- PASS: TestConsulSecretBackend_WriteOnlyBoth (3.92s)
--- PASS: TestConsulSecretBackend_WriteOnlyToken (4.01s)
=== NAME  TestConsulSecretBackend_ComputedTokenWithConsul
    resource_consul_secret_backend_test.go:561: Vault server version "1.21.0+ent"
--- PASS: TestConsulSecretBackend_remount (6.80s)
--- PASS: TestConsulSecretBackend_CustomizeDiff (8.42s)
--- PASS: TestConsulSecretBackend (9.73s)
--- PASS: TestConsulSecretBackendRole (9.87s)
--- PASS: TestConsulSecretBackend_ComputedTokenWithConsul (11.19s)
--- PASS: TestConsulSecretBackend_Bootstrap (11.79s)
PASS
ok      github.com/hashicorp/terraform-provider-vault/vault     12.584s
...
```

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

## PCI review checklist

- [ ] I have documented a clear reason for, and description of, the change I am making.

- [ ] If applicable, I've documented a plan to revert these changes if they require more than reverting the pull request.

- [ ] If applicable, I've documented the impact of any changes to security controls.

  Examples of changes to security controls include using new access control methods, adding or removing logging pipelines, etc.

### CODE REVIEW

File: vault/resource_consul_secret_backend_test.go [hunk 1]
```diff
@@ -478,6 +478,57 @@ func TestConsulSecretBackend_WriteOnlyConflicts(t *testing.T) {
 	})
 }
 
+func TestConsulSecretBackend_CustomizeDiff(t *testing.T) {
```
Comment (Balaji2198) [inline vault/resource_consul_secret_backend_test.go:481]: Can we add a test case with `bootstrap = true` and a computed token field is present with the expectation that it should fail?

File: vault/resource_consul_secret_backend.go [hunk 2]
```diff
@@ -361,29 +360,27 @@ func consulSecretBackendConfigPath(backend string) string {
...
+	isTokenWOKnown := diff.NewValueKnown(consts.FieldTokenWO)
+
+	hasTokenValue := newToken != "" || newTokenWO != ""
+	tokenIsDefinitelyEmpty := (isTokenKnown && newToken == "") && (isTokenWOKnown && newTokenWO == "")
+
+	if newBootstrap {
+		// CASE: Bootstrap mode is ON
+		// We disallow a token if it's explicitly provided OR if it's being computed.
+		// If bootstrap is true, the HCL should not contain token/token_wo at all.
+		if hasTokenValue || !isTokenKnown || !isTokenWOKnown {
```
Comment (vijayavelsekar) [inline vault/resource_consul_secret_backend.go:377]: Can we simplify the conditional check with just 2 checks to see if the token and token_wo is present in the config file or not ?

**Example:**
```
func consulSecretsBackendCustomizeDiff(ctx context.Context, diff *schema.ResourceDiff, meta interface{}) error {
	newBootstrap := diff.Get("bootstrap").(bool)

	// Check if token fields are present in the configuration
	rawConfig := diff.GetRawConfig()
	tokenInConfig := !rawConfig.GetAttr("token").IsNull()
	tokenWOInConfig := !rawConfig.GetAttr(consts.FieldTokenWO).IsNull()

	hasAnyTokenField := tokenInConfig || tokenWOInConfig

	if newBootstrap {
		// Bootstrap mode: token fields should NOT be in the configuration
		if hasAnyTokenField {
			return fmt.Errorf("field 'bootstrap' must be set to false when 'token' or 'token_wo' is specified or computed")
		}
	} else {
		// Standard mode: at least one token field MUST be in the configuration
		if !hasAnyTokenField {
			return fmt.Errorf("field 'bootstrap' must be set to true when neither 'token' nor 'token_wo' is specified")
		}
	}

	// check whether mount migration is required
	f := getMountCustomizeDiffFunc(consts.FieldPath)
	return f(ctx, diff, meta)
}
```

Comment (vijayavelsekar) [reply vault/resource_consul_secret_backend.go:377]: In your logic. For bootstrap true and if we pass empty token="" its passing. Which does not matter as the token will not be sent to the server, which will cause bootstrapping in the server.
In the proposed logic.  For bootstrap false and if we pass empty token="" its passing. But in this case, the bootstrapping will be done in the server side, but its misleading to see bootstrap false in the terraform side.
So comparatively, we should proceed with your logic.

**Review by vijayavelsekar — DISMISSED** [review]
LGTM

**Review by vijayavelsekar — APPROVED** [review]

**Comment by greut** [comment]
Thanks @Siddharth-Kannan
