### PR TITLE
VAULT-37696: vault_plugin support for enterprise plugins

### LINKED ISSUE #2518: [Enhancement]: vault_plugin support for enterprise plugins
### Description

I use the `vault-plugin-database-oracle` plugin, which I see now offers an enterprise build.

Reviewing the Vault and Vault provider documentation, registering the plugin does not require the SHA256 checksum to register, but the `vault_plugin` resource requires a `sha256` parameter. I tried to register the `0.12.3+ent` version of the plugin using the `vault_plugin` resource, with and without a SHA value, and got the failed results shown below.

It would be useful if the `vault_plugin` resources was able to support enterprise plugins.

With:
```
╷
│ Error: error updating plugin "database/version/0.12.3+ent/name/vault-plugin-database-oracle": Error making API request.
│ 
│ URL: PUT http://127.0.0.1:7200/v1/sys/plugins/catalog/database/vault-plugin-database-oracle
│ Code: 400. Errors:
│ 
│ * enterprise plugin should only specify version and not sha256
│ 
│   with vault_plugin.database_oracle,
│   on main.tf line 23, in resource "vault_plugin" "database_oracle":
│   23: resource "vault_plugin" "database_oracle" {
│ 
╵

```

Without:
```
╷
│ Error: Missing required argument
│ 
│   on main.tf line 23, in resource "vault_plugin" "database_oracle":
│   23: resource "vault_plugin" "database_oracle" {
│ 
│ The argument "sha256" is required, but no definition was found.
╵

```

### Affected Resource(s) and/or Data Source(s)

* vault_plugin

### Potential Terraform Configuration

```terraform
resource "vault_plugin" "database_oracle_ent" {
    type = "database"
    name = "vault-plugin-database-oracle"
    command = "vault-plugin-database-oracle"
    version = "0.12.3+ent"
}
```

### References

* [vault_plugin resource](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/plugin#sha256-1)
* [register enterprise plugins](https://developer.hashicorp.com/vault/docs/plugins/plugin-management#enterprise-plugins)

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by chpag**
### Description

This PR allow to use vault_plugin ressource for Vault Enterprise Plugin
As the sha256 should not be defined for enterprise plugin,  it has been changed from mandatory to Optional
command attributes has also been marked as Optional as Enterprise plugin ignore the value
An additional check has been added in CustomizeDiff for
   - if enterprise plugin (plugin version ending with "+ent")
      - sha256 should be empty
      - command should be empty
   - else (not enterprise plugin)
      - sha256 should not be empty
      - command should not be empty

pluginIDRegex Regular Expression has been updated to allow "+" character in the version to allow "+ent"

when plugin is Enterprise, exclude sha256 from the attribute retrieved by pluginRead(), so there is no mismatch between what is defined in the hcl code and what is put on the state file

Update also build.yml to add Enteprise plugin download and ENV variables set

Closes #2518

### Checklist
- [X] Added [CHANGELOG](https://github.com/hashicorp/terraform-provider-vault/blob/master/CHANGELOG.md) entry (only for user-facing changes)
- [X] Acceptance tests where run against all supported Vault Versions

### Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

## PCI review checklist

- [X] I have documented a clear reason for, and description of, the change I am making.

- [X] If applicable, I've documented a plan to revert these changes if they require more than reverting the pull request.

- [X] If applicable, I've documented the impact of any changes to security controls.

  Examples of changes to security controls include using new access control methods, adding or removing logging pipelines, etc.

### CODE REVIEW

File: vault/resource_plugin.go [hunk 1]
```diff
@@ -289,3 +296,17 @@ func diffSuppressEqualSemver(_, oldValue, newValue string, _ *schema.ResourceDat
 	}
 	return false
 }
+
+func pluginCustomizeDiff(ctx context.Context, d *schema.ResourceDiff, meta interface{}) error {
+	curVersion := d.Get(consts.FieldVersion).(string)
+	if strings.HasSuffix(curVersion, "+ent") {
+		if d.Get(fieldSHA256).(string) != "" {
+			return fmt.Errorf("field %s need to be empty for enteprise plugin", fieldSHA256)
```
Comment (siyer-corp) [inline vault/resource_plugin.go]: There's a typo in _enterprise_ and _need_ can be replaced by _needs_

File: vault/resource_plugin.go [hunk 2]
```diff
@@ -289,3 +296,17 @@ func diffSuppressEqualSemver(_, oldValue, newValue string, _ *schema.ResourceDat
...
+		}
+	} else {
+		if d.Get(fieldSHA256).(string) == "" {
+			return fmt.Errorf("field %s need to be set for non enteprise plugin", fieldSHA256)
```
Comment (siyer-corp) [inline vault/resource_plugin.go]: There's a typo in _enterprise_ and _need_ can be replaced by _needs_

File: vault/resource_plugin_test.go [hunk 3]
```diff
@@ -81,6 +84,48 @@ func TestPlugin(t *testing.T) {
...
+
+		argsUpdated = `["--bar"]`
+		envUpdated  = `["FOO=BAZ"]`
+	)
+
+	resourceName := "vault_plugin.test"
+
+	// VAULT_PLUGIN_ENT_NAME, VAULT_PLUGIN_ENT_COMMAND,VAULT_PLUGIN_ENT_VERSION should be set to the name of the plugin executable
+	// in the configured plugin_directory for Vault.
+	name := os.Getenv(envPluginEntName)
```
Comment (siyer-corp) [inline vault/resource_plugin_test.go:101]: Could we test these changes with constants instead of env vars for ent and and non-ent versions?

File: vault/resource_plugin.go (hunk 1 above)
Comment (chpag) [reply vault/resource_plugin.go]: Typo fixed

File: vault/resource_plugin.go (hunk 2 above)
Comment (chpag) [reply vault/resource_plugin.go]: Type fixed

File: vault/resource_plugin_test.go (hunk 3 above)
Comment (chpag) [reply vault/resource_plugin_test.go:101]: @siyer-corp, I replace the name with a constant, but for the others, to be able to do the enteprise test you should have the enterprise plugin available on the testing environment, so I don't know what should be the good way to integrate an enterprise plugin in the testing environment

**Review by fairclothjm — COMMENTED** [review]
Thanks! Can we also update the docs page since sha is not required except for CE plugins? https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/plugin#sha256-1

File: website/docs/r/plugin.html.md [hunk 4]
```diff
@@ -39,6 +41,17 @@ resource "vault_auth_backend" "jwt_auth" {
 }
 ```
 
+Register an enterprise plugin
```
Comment (fairclothjm) [inline website/docs/r/plugin.html.md]:
```suggestion
### Register an official enterprise plugin

The `version` is required for enterprise plugins.
```

Comment (fairclothjm) [reply website/docs/r/plugin.html.md]: nit: can we move this to be the first example so it is more prominent?

File: website/docs/r/plugin.html.md [hunk 5]
```diff
@@ -22,6 +22,8 @@ For more information on managing external plugins, please refer to the Vault
 
 ## Example Usage
 
+Register a standard plugin
```
Comment (fairclothjm) [inline website/docs/r/plugin.html.md]:
```suggestion
### Register a CE plugin

The `sha256` is required to register a CE plugin.
```

File: website/docs/r/plugin.html.md [hunk 6]
```diff
@@ -49,7 +62,7 @@ The following arguments are supported:
 
 * `version` - (Optional) Semantic version of the plugin.
```
Comment (fairclothjm) [inline website/docs/r/plugin.html.md]:
```suggestion
* `version` - (Optional) Semantic version of the plugin. Required for official enterprise plugins.
```

**Review by fairclothjm — COMMENTED** [review]
Looking great! Left some suggestions

File: vault/resource_plugin.go
Comment (siyer-corp) [inline vault/resource_plugin.go]: @fairclothjm, @chpag Quick question, should command be Optional too? In the [documentation](https://developer.hashicorp.com/vault/docs/plugins/register#step-2-update-the-plugin-catalog), it's not a required field for ent plugins registered via the .zip files.

Comment (chpag) [reply vault/resource_plugin.go]: @siyer-corp : you're right command should be optional too if enterprise (as it's ignored), so I marked it as Optional and also add a check in Diff to verify command is defined if non enterprise

Comment (chpag) [reply vault/resource_plugin.go]: Need to redo additionnal check regarding command and name

Comment (chpag) [reply vault/resource_plugin.go]: Fix command that should be empty for enterprise plugin as registered via zip. Add steps to build.yml to download an Enterprise plugin and test the resource_plugin usage with enterprise Plugin

**Review by siyer-corp — APPROVED** [review]
Thank you, LGTM!
