### PR TITLE
Ensure that the ca_chain is populated, add new certificate_bundle field to pki_secret_backend_root_sign_intermediate

### LINKED ISSUE #684: ca_chain output is empty
### Terraform Version
Terraform v0.12.21
+ provider.local v1.4.0
+ provider.tls v2.1.1
+ provider.vault v2.4.4

### Affected Resource(s)
- vault_pki_secret_backend_root_sign_intermediate

### Terraform Configuration Files
```hcl
resource "vault_mount"  "root" {
    type = "pki"
    path = "pki-ca-test"
    default_lease_ttl_seconds = 31556952 
    max_lease_ttl_seconds = 157680000 
    description = "Root Certificate Authority"
}

resource "vault_mount" "pki_int" {
    type = "pki"
    path = "pki-int-ca-test"
    default_lease_ttl_seconds = 63072000
    max_lease_ttl_seconds = 63072000 
    description = "Intermediate Authority for test.com"
}

resource "vault_pki_secret_backend_intermediate_cert_request" "intermediate" {
  backend = vault_mount.pki_int.path
  type = "exported"
  common_name = "Test Intermediate Certificate"
  format = "pem"
  private_key_format = "der"
  key_type = "rsa"
  key_bits = "2048"
}
resource "vault_pki_secret_backend_root_sign_intermediate" "intermediate" {
  backend = vault_mount.root.path
  csr = vault_pki_secret_backend_intermediate_cert_request.intermediate.csr
  common_name = "Test Intermediate Certificate"
  exclude_cn_from_sans = true
  ou = "Development"
  organization = "test.com"
  ttl = 31536000
}
output "chain"  {
    value = vault_pki_secret_backend_root_sign_intermediate.intermediate.ca_chain
}

```

### Expected Behavior
Certificates chain

### Actual Behavior
empty output

### Steps to Reproduce
1. `terraform apply`
 or maybe i don't  understand how it works.

### PR DESCRIPTION
**Pull request by benashz**
Compute the ca_chain from the response.

- add new string field `certificate_bundle` that is the concatenation of the intermediate CA and its issuer.
- Factor out a single TestCheckFunc for all tests
- update test configuration to provide distinct field values
- other fixes

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #684 

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vault/blob/master/CHANGELOG.md):

```release-note

```

Output from acceptance testing:

```
$ make testacc TESTARGS='-count=1 -test.run Test.+Secret.+Intermediate'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test -v -count=1 -test.run Test.+Secret.+Intermediate -timeout 30m ./...

ok      github.com/hashicorp/terraform-provider-vault/util      0.409s [no tests to run]
=== RUN   TestPkiSecretBackendIntermediateCertRequest_basic
--- PASS: TestPkiSecretBackendIntermediateCertRequest_basic (2.42s)
=== RUN   TestPkiSecretBackendIntermediateSetSigned_basic
--- PASS: TestPkiSecretBackendIntermediateSetSigned_basic (3.92s)
=== RUN   TestPkiSecretBackendRootSignIntermediate_basic_default
--- PASS: TestPkiSecretBackendRootSignIntermediate_basic_default (3.25s)
=== RUN   TestPkiSecretBackendRootSignIntermediate_basic_pem
--- PASS: TestPkiSecretBackendRootSignIntermediate_basic_pem (2.63s)
=== RUN   TestPkiSecretBackendRootSignIntermediate_basic_der
--- PASS: TestPkiSecretBackendRootSignIntermediate_basic_der (3.04s)
=== RUN   TestPkiSecretBackendRootSignIntermediate_basic_pem_bundle
--- PASS: TestPkiSecretBackendRootSignIntermediate_basic_pem_bundle (2.53s)
=== RUN   Test_pkiSecretRootSignIntermediateRUpgradeV0
=== RUN   Test_pkiSecretRootSignIntermediateRUpgradeV0/basic
=== RUN   Test_pkiSecretRootSignIntermediateRUpgradeV0/invalid-no-issuing-ca
=== RUN   Test_pkiSecretRootSignIntermediateRUpgradeV0/invalid-no-certificate
--- PASS: Test_pkiSecretRootSignIntermediateRUpgradeV0 (0.00s)
    --- PASS: Test_pkiSecretRootSignIntermediateRUpgradeV0/basic (0.00s)
    --- PASS: Test_pkiSecretRootSignIntermediateRUpgradeV0/invalid-no-issuing-ca (0.00s)
    --- PASS: Test_pkiSecretRootSignIntermediateRUpgradeV0/invalid-no-certificate (0.00s)
PASS
ok      github.com/hashicorp/terraform-provider-vault/vault     19.550s

...
```

### CODE REVIEW

File: vault/resource_pki_secret_backend_root_sign_intermediate_test.go [hunk 1]
```diff
@@ -14,32 +15,149 @@ import (
...
-				),
+				Config: testPkiSecretBackendRootSignIntermediateConfig_basic(rootPath, intermediatePath, ""),
+				Check:  testCheckPKISecretRootSignIntermediate("vault_pki_secret_backend_root_sign_intermediate.test", rootPath, format),
 			},
 		},
 	})
 }
 
+func TestPkiSecretBackendRootSignIntermediate_basic_pem(t *testing.T) {
+	path := "pki-root-" + strconv.Itoa(acctest.RandInt())
```
Comment (vinay-gopalan) [inline vault/resource_pki_secret_backend_root_sign_intermediate_test.go:37]: nit: should we keep the variable names consistent for all 3 `basic` tests? Perhaps `rootPath` and `intermediatePath`

Comment (benashz) [reply vault/resource_pki_secret_backend_root_sign_intermediate_test.go]: Fixed in https://github.com/hashicorp/terraform-provider-vault/pull/1330/commits/db3ac9f89a2d030d6de3aa9d6eeb8f976a480cb9

**Review by vinay-gopalan — APPROVED** [review]
