### PR TITLE
Data source vault auth backends

### LINKED ISSUE #1081: FEATURE data "vault_auth_backends"
Provide a way to query all auth backends as tuple of maps or map of maps

### Terraform Version
n/a

### Affected Resource(s)
vault_auth_backend

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
n/a 

### Debug Output
n/a

### Panic Output
n/a

### Expected Behavior
return a tuple with all the backend available

### Actual Behavior
not implemented / possible

### Steps to Reproduce
n/a

### Important Factoids
n/a

### References
n/a

### LINKED ISSUE #1793: Data source: vault_auth_backends
### Terraform Version
1.3.3

### Affected Resource(s)
- NEW: vault_auth_backends

### Terraform Configuration Files
```hcl
resource "vault_auth_backend" "test1" {
	type = "userpass"
	path = "test-up"
}

resource "vault_auth_backend" "test2" {
	type = "userpass"
	path = "test-up2"
}

resource "vault_auth_backend" "test3" {
	type = "approle"
	path = "test-ar"
}

resource "vault_auth_backend" "test4" {
	type = "approle"
	path = "test-ar2"
}

data "vault_auth_backends" "test" { }
```

### Debug Output
In developing this data source, I've come across the following issues while doing testing, and also have a problem determining the `id` to set for this data source.

```text
2023/03/13 16:38:03 [INFO] Using Vault token with the following policies: root
--- FAIL: TestDataSourceAuthBackends (0.41s)
    testing_new_config.go:82: no "id" found in attributes
    testing_new.go:62: no "id" found in attributes
FAIL
FAIL    github.com/hashicorp/terraform-provider-vault/vault     0.798s
FAIL
make: *** [testacc] Error 1
```

The relevant files for developing this feature can be found here: https://github.com/hashicorp/terraform-provider-vault/compare/main...mengesb:terraform-provider-vault:data-source-vault-auth-backends

### Panic Output
N/A

### Expected Behavior
Clean tests, functional new data source

### Actual Behavior
Erroring tests, incomplete `d.SetId()` function on data source

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Clone my fork
2. `vault server -dev`
3. `export VAULT_ADDR=http://127.0.0.1:8200`
4. `export VAULT_TOKEN=...content from vault dev server run...`
5. `export TESTARGS="--run TestDataSourceAuthBackends"`
6. `GOPATH=$CWD make build`
7. `GOPATH=$CWD make testacc`

### Important Factoids
developing new data source

### References
- Addresses GH-1081

### PR DESCRIPTION
**Pull request by mengesb**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #1793
Closes #1081 

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vault/blob/master/CHANGELOG.md):

```release-note
FEATURES:
* Add new data source `vault_auth_backends`, test fixup by @fairclothjm
```

Output from acceptance testing:

```text
$ vault server -dev >vault-server-dev.log 2>&1 &
$ export TESTARGS="--run TestDataSourceAuthBackends"
$ export VAULT_ADDR='http://127.0.0.1:8200'
$ export VAULT_TOKEN=REDACTED
$ GOPATH=$CWD make testacc
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test --run TestDataSourceAuthBackends -timeout 30m ./...
?       github.com/hashicorp/terraform-provider-vault   [no test files]
?       github.com/hashicorp/terraform-provider-vault/cmd/coverage      [no test files]
?       github.com/hashicorp/terraform-provider-vault/cmd/generate      [no test files]
?       github.com/hashicorp/terraform-provider-vault/generated [no test files]
ok      github.com/hashicorp/terraform-provider-vault/codegen   (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/datasources/transform/decode(cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/datasources/transform/encode(cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/resources/transform/alphabet(cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/resources/transform/role   (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/resources/transform/template(cached) [no tests to run]
?       github.com/hashicorp/terraform-provider-vault/helper    [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/consts   [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/identity/group   [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/identity/mfa     [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/pki      [no test files]
?       github.com/hashicorp/terraform-provider-vault/schema    [no test files]
ok      github.com/hashicorp/terraform-provider-vault/generated/resources/transform/transformation  (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/internal/identity/entity  (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/internal/provider (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/testutil  (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/util      (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/vault     3.377s
```

### CODE REVIEW

File: vault/data_source_auth_backends_test.go [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+	type = "userpass"
+}
+resource "vault_auth_backend" "test-bar" {
+	path = "%s"
+	type = "approle"
+}
+data "vault_auth_backends" "test" {
+	depends_on = [
+		"vault_auth_backend.test-foo",
+		"vault_auth_backend.test-bar",
```
Comment (fairclothjm) [inline vault/data_source_auth_backends_test.go:91]: I know it is a test but Quoted references are deprecated and may be removed in future versions so we should probably remove them.
```suggestion
		vault_auth_backend.test-foo,
		vault_auth_backend.test-bar,
```

File: vault/data_source_auth_backends.go [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+		}
+	}
+
+	// Single instance data source - defaulting ID to 'default'
+	d.SetId("default")
+	d.Set("paths", paths)
+	d.Set("type", targetType)
+	d.Set("accessors", accessors)
+
+	// If we fell out here then we didn't find our Auth in the list.
```
Comment (fairclothjm) [inline vault/data_source_auth_backends.go:78]: I don't think this comment is necessarily true. Can we remove it?

File: website/docs/d/auth_backends.html.md [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+## Argument Reference
+
+The following arguments are supported:
+
+* `namespace` - (Optional) The namespace of the target resource.
+  The value should not contain leading or trailing forward slashes.
+  The `namespace` is always relative to the provider's configured [namespace](/docs/providers/vault#namespace).
+  *Available only for Vault Enterprise*.
+
+* `type` - (Optional) The name of the auth method type.
```
Comment (fairclothjm) [inline website/docs/d/auth_backends.html.md:31]: This describes what this field is but could we provide a little information on what this does?

File: vault/data_source_auth_backends.go [hunk 4]
```diff
@@ -0,0 +1,80 @@
...
+	return &schema.Resource{
+		Read: ReadWrapper(authBackendsDataSourceRead),
+		Schema: map[string]*schema.Schema{
+			"paths": {
+				Type:        schema.TypeList,
+				Computed:    true,
+				Elem:        &schema.Schema{Type: schema.TypeString},
+				Description: "The auth backend mount points.",
+			},
+			"type": {
```
Comment (fairclothjm) [inline vault/data_source_auth_backends.go:26]: Can we use consts for each of these? If not already defined in https://github.com/hashicorp/terraform-provider-vault/blob/main/internal/consts/consts.go then we can add new entries.
```suggestion
			consts.FieldType: {
```

File: vault/data_source_auth_backends.go [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+	for path, auth := range auths {
+
+		path = strings.TrimSuffix(path, "/")
+
+		if targetType == "" {
+			paths = append(paths, path)
+			accessors = append(accessors, auth.Accessor)
+			// we do this to make test assertions easier
+			// this is not required
+			sort.Strings(paths)
```
Comment (fairclothjm) [inline vault/data_source_auth_backends.go:65]: This doesn't seem to be required for the tests to pass. I don't know why I added it 🤔 . Can we remove it?

File: vault/data_source_auth_backends_test.go [hunk 6]
```diff
@@ -0,0 +1,96 @@
...
+resource "vault_auth_backend" "userpass" {
+	type = "userpass"
+}
+resource "vault_auth_backend" "approle" {
+	type = "approle"
+}
+data "vault_auth_backends" "test" {
+	depends_on = [
+		"vault_auth_backend.userpass",
+		"vault_auth_backend.approle",
```
Comment (fairclothjm) [inline vault/data_source_auth_backends_test.go:73]: I know it is a test but Quoted references are deprecated and may be removed in future versions so we should probably remove them.

**Review by fairclothjm — COMMENTED** [review]
Thanks @mengesb! Just a few small changes and this should be good to go!

File: vault/data_source_auth_backends.go (hunk 2 above)
Comment (mengesb) [reply vault/data_source_auth_backends.go:78]: This was adopted from `data.auth_backend`; I'll remove it

File: vault/data_source_auth_backends.go (hunk 5 above)
Comment (mengesb) [reply vault/data_source_auth_backends.go:65]: I'll remove it and re-run the tests to be sure. The tests depended on an order, not sure if that will upset tests; will verify

Comment (mengesb) [reply vault/data_source_auth_backends.go:65]:
```text
--- FAIL: TestDataSourceAuthBackends (2.04s)
    data_source_auth_backends_test.go:22: Step 2/3 error: Check failed: Check 2/6 error: data.vault_auth_backends.test: Attribute 'paths.0' expected "approle", got "userpass"
FAIL
FAIL    github.com/hashicorp/terraform-provider-vault/vault     2.385s
FAIL
make: *** [testacc] Error 1
```

So I can update comparison order, however is it possible that the order would change based on the testing conditions I've supplied?

Comment (mengesb) [reply vault/data_source_auth_backends.go:65]: So the first time I run the test, it fails, but subsequent runs pass successfully (with the sort removed)

File: website/docs/d/auth_backends.html.md (hunk 3 above)
Comment (fairclothjm) [reply website/docs/d/auth_backends.html.md:31]: Yes

**Comment by fairclothjm** [comment]
@mengesb RE: consts

Yes, let's update all fields to use consts. If not already defined in https://github.com/hashicorp/terraform-provider-vault/blob/main/internal/consts/consts.go then we can add new entries.

> data.auth_backend doesn't make use of consts

We are requiring that all new resources use consts.

**Comment by mengesb** [comment]
```text
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test --run TestDataSourceAuthBackends -timeout 30m ./...
?       github.com/hashicorp/terraform-provider-vault   [no test files]
?       github.com/hashicorp/terraform-provider-vault/cmd/coverage      [no test files]
?       github.com/hashicorp/terraform-provider-vault/cmd/generate      [no test files]
?       github.com/hashicorp/terraform-provider-vault/generated [no test files]
ok      github.com/hashicorp/terraform-provider-vault/codegen   (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/datasources/transform/decode  (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/datasources/transform/encode  (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/resources/transform/alphabet  (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/resources/transform/role      (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/resources/transform/template  (cached) [no tests to run]
?       github.com/hashicorp/terraform-provider-vault/helper    [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/consts   [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/identity/group   [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/identity/mfa     [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/pki      [no test files]
?       github.com/hashicorp/terraform-provider-vault/schema    [no test files]
ok      github.com/hashicorp/terraform-provider-vault/generated/resources/transform/transformation     (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/internal/identity/entity  (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/internal/provider (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/testutil  (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/util      (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/vault     3.127s
```

File: vault/data_source_auth_backends_test.go (hunk 6 above)
Comment (mengesb) [reply vault/data_source_auth_backends_test.go]: This should now be resolved

File: vault/data_source_auth_backends.go (hunk 5 above)
Comment (mengesb) [reply vault/data_source_auth_backends.go:66]: Re-added the sort to ensure tests are consistent. Unless you think it's better to sort only in the test, I'll leave this as-is for now. LMK if you think this is OK and resolved

File: website/docs/d/auth_backends.html.md (hunk 3 above)
Comment (mengesb) [reply website/docs/d/auth_backends.html.md]: I added a few more words - LMK if this is to your liking ;)

**Comment by mengesb** [comment]
Myriad of comments, commits, and overall byte sized goodness.

File: vault/data_source_auth_backends.go [hunk 7]
```diff
@@ -0,0 +1,80 @@
...
+				Elem:        &schema.Schema{Type: schema.TypeString},
+				Description: "The auth backend mount points.",
+			},
+			consts.FieldType: {
+				Type:        schema.TypeString,
+				Optional:    true,
+				Description: "The type of the auth backend.",
+			},
+			consts.FieldAuthMethodAccessors: {
+				//"accessors": {
```
Comment (fairclothjm) [inline vault/data_source_auth_backends.go:32]:
```suggestion
```

File: vault/data_source_auth_backends.go [hunk 8]
```diff
@@ -0,0 +1,80 @@
...
+				Computed:    true,
+				Elem:        &schema.Schema{Type: schema.TypeString},
+				Description: "The auth backend mount points.",
+			},
+			consts.FieldType: {
+				Type:        schema.TypeString,
+				Optional:    true,
+				Description: "The type of the auth backend.",
+			},
+			consts.FieldAuthMethodAccessors: {
```
Comment (fairclothjm) [inline vault/data_source_auth_backends.go:31]: I prefer the name `accessors` since this name stutters:

`data.vault_auth_backends.test.auth_method_accessors`

vs

`data.vault_auth_backends.test.accessors`

Also the existing `vault_auth_backend` resource uses `accessor` so I think it makes sense to be similar to that.

File: vault/data_source_auth_backends.go (hunk 5 above)
Comment (fairclothjm) [reply vault/data_source_auth_backends.go:66]: I think it is better to sort only in the test. But if we can't do that then I don't see a problem with leaving this as-is. I will leave it up to you.

File: vault/data_source_auth_backends_test.go [hunk 9]
```diff
@@ -0,0 +1,96 @@
...
+		Providers: testProviders,
+		PreCheck:  func() { testutil.TestAccPreCheck(t) },
+		Steps: []r.TestStep{
+			{
+				Config: testDataSourceAuthBackendsBasic,
+				// The token auth method is built-in and automatically enabled
+				Check: resource.ComposeTestCheckFunc(
+					resource.TestCheckResourceAttr(ds, "paths.#", "1"),
+					resource.TestCheckResourceAttr(ds, "paths.0", "token"),
+					resource.TestCheckResourceAttr(ds, "auth_method_accessors.#", "1"),
```
Comment (fairclothjm) [inline vault/data_source_auth_backends_test.go:32]: Can we use consts for all the field references?

**Comment by mengesb** [comment]
```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test --run TestDataSourceAuthBackends -timeout 30m ./...
?       github.com/hashicorp/terraform-provider-vault   [no test files]
?       github.com/hashicorp/terraform-provider-vault/cmd/coverage      [no test files]
?       github.com/hashicorp/terraform-provider-vault/cmd/generate      [no test files]
?       github.com/hashicorp/terraform-provider-vault/generated [no test files]
ok      github.com/hashicorp/terraform-provider-vault/codegen   (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/datasources/transform/decode(cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/datasources/transform/encode(cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/resources/transform/alphabet(cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/resources/transform/role   (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/resources/transform/template(cached) [no tests to run]
?       github.com/hashicorp/terraform-provider-vault/helper    [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/consts   [no test files]
ok      github.com/hashicorp/terraform-provider-vault/generated/resources/transform/transformation  (cached) [no tests to run]
?       github.com/hashicorp/terraform-provider-vault/internal/identity/group   [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/identity/mfa     [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/pki      [no test files]
ok      github.com/hashicorp/terraform-provider-vault/internal/identity/entity  (cached) [no tests to run]
?       github.com/hashicorp/terraform-provider-vault/schema    [no test files]
ok      github.com/hashicorp/terraform-provider-vault/internal/provider (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/testutil  (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/util      (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/vault     3.140s
```

**Comment by mengesb** [comment]
OK

I updated the tests to uses `consts`, and also found my IDE warned me about a duplicate use of `terraform-plugin-sdk/v2/helper/resource` so I removed the renamed import and updated those references. I also added the new const `FieldAccessors` since there was no other plural `accessor` const.

**Review by fairclothjm — COMMENTED** [review]
One last nitpick and this PR can be merged

File: vault/data_source_auth_backends.go (hunk 5 above)
Comment (fairclothjm) [reply vault/data_source_auth_backends.go:65]: I think this is probably better since the sort operation isn't required in the source. Only thing I would suggest is to add a comment on why you are sorting in the test. Thanks!

Comment (mengesb) [reply vault/data_source_auth_backends.go:65]: OK, getting this pushed in

**Comment by mengesb** [comment]
```text
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test --run TestDataSourceAuthBackends -timeout 30m ./...
?       github.com/hashicorp/terraform-provider-vault   [no test files]
?       github.com/hashicorp/terraform-provider-vault/cmd/coverage      [no test files]
?       github.com/hashicorp/terraform-provider-vault/cmd/generate      [no test files]
?       github.com/hashicorp/terraform-provider-vault/generated [no test files]
ok      github.com/hashicorp/terraform-provider-vault/codegen   (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/datasources/transform/decode0.376s [no tests to run]
?       github.com/hashicorp/terraform-provider-vault/internal/consts   [no test files]
?       github.com/hashicorp/terraform-provider-vault/helper    [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/identity/group   [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/identity/mfa     [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/pki      [no test files]
?       github.com/hashicorp/terraform-provider-vault/schema    [no test files]
ok      github.com/hashicorp/terraform-provider-vault/generated/datasources/transform/encode0.686s [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/resources/transform/alphabet0.987s [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/resources/transform/role   1.305s [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/resources/transform/template1.593s [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/resources/transform/transformation  1.401s [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/internal/identity/entity  (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/internal/provider (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/testutil  (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/util      (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/vault     3.175s
```

**Comment by mengesb** [comment]
OK, we're all `consts`-ed; sort from data source removed so there's no implied order, and the `type` field documentation was amended to help explain it a little better. We bounced around on `accessors` due to `consts`, but we're back with `accessors` being a `consts` so I think we're good there.

Hope everything is looking 👍

**Review by fairclothjm — APPROVED** [review]
LGTM! Thanks @mengesb !
