### PR TITLE
Handle host prefix stripped token_bound_cidrs

### LINKED ISSUE #1322: Resource vault_approle_auth_backend_role strips netmask from token_bound_cidrs leading to repeated apply
### Terraform Version
$ terraform -v
Terraform v1.1.3
on darwin_amd64

### Affected Resource(s)
Please list the resources as a list, for example:
- vault_approle_auth_backend_role

### Terraform Configuration Files
```hcl
resource "vault_approle_auth_backend_role" "role" {
  backend                 = "approle"
  role_name               = "role_1"
  secret_id_bound_cidrs   = ["10.0.0.1/32"]
  secret_id_ttl           = 0
  token_policies          = ["policy_1"]
  token_num_uses          = 0
  token_bound_cidrs       = ["10.0.0.1/32"]
}
```

### Expected Behavior
Terraform should add "10.0.0.1/32" to the token_bound_cidrs

### Actual Behavior
Terraform strips the `/32` from the entry, causing Terraform to re-apply it on every run:

```
  # module.approles["role_1"].vault_approle_auth_backend_role.role has changed
  ~ resource "vault_approle_auth_backend_role" "role" {
        id                      = "auth/approle/role/role_1"
      ~ token_bound_cidrs       = [
          + "10.0.0.1",
          - "10.0.0.1/32",
        ]
        # (15 unchanged attributes hidden)
    }
```

Vault from a functional perspective accepts the IP address without `/32`, so this is not a functional issue apart from our CI pipeline showing a change every time we run it. I have not tested if Terraform will strip larger netmasks from the IP as well (for example a `/24`

Please note that this error does _not_ happen with the `secret_id_bound_cidrs`, only `token_bound_cidrs`. 

### Workaround (in case anyone else finds this issue):

```
resource "vault_approle_auth_backend_role" "role" {
  backend                 = "approle"
  role_name               = "role_1"
  secret_id_bound_cidrs   = ["10.0.0.1/32"]
  secret_id_ttl           = 0
  token_policies          = ["policy_1"]
  token_num_uses          = 0
  token_bound_cidrs       = [split("/","10.0.0.1/32")[0]]
}
```

### Steps to Reproduce

1. Create the HCL as defined above
2. Terraform apply
3. Terraform apply a second time

### References
I was unable to find any other issues referencing this

### PR DESCRIPTION
**Pull request by benashz**
The `token_bound_cidrs` returned from Vault have the host prefix stripped. The issue affects both IPv4 and IPv6 host addresses.

This PR adds a fix that will append the correct CIDR prefix to any host that has been stripped by Vault. In the case where a host address has not been configured explicitly with a prefix no prefix will be appended.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #1322 

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vault/blob/master/CHANGELOG.md):

```release-note

```

Output from acceptance testing:

```
$ make testacc TESTARGS='-v -test.run TestAccTokenAuthBackendRole'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test -v -v -test.run TestAccTokenAuthBackendRole -timeout 30m ./...

PASS
ok      github.com/hashicorp/terraform-provider-vault/util      (cached) [no tests to run]
=== RUN   TestAccTokenAuthBackendRoleImport
--- PASS: TestAccTokenAuthBackendRoleImport (2.68s)
=== RUN   TestAccTokenAuthBackendRole
--- PASS: TestAccTokenAuthBackendRole (2.05s)
=== RUN   TestAccTokenAuthBackendRoleUpdate
--- PASS: TestAccTokenAuthBackendRoleUpdate (6.14s)
PASS
ok      github.com/hashicorp/terraform-provider-vault/vault     11.348s

make testacc TESTARGS='-v -test.run Test_handleCIDRField'       
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test -v -v -test.run Test_handleCIDRField -timeout 30m ./...

=== RUN   Test_handleCIDRField
=== RUN   Test_handleCIDRField/basic
--- PASS: Test_handleCIDRField (0.00s)
    --- PASS: Test_handleCIDRField/basic (0.00s)
PASS
ok      github.com/hashicorp/terraform-provider-vault/vault     1.841s
```

### CODE REVIEW

File: vault/auth_token.go [hunk 1]
```diff
@@ -276,14 +277,76 @@ func updateTokenFields(d *schema.ResourceData, data map[string]interface{}, crea
...
+
+			var bits int
+			if m := ip.DefaultMask(); m != nil {
+				// IPv4
+				_, bits = m.Size()
+			} else {
+				// IPv6
+				bits = 128
+			}
+			// addrs = append(addrs, fmt.Sprintf("%s/%d", addr, bits))
```
Comment (vinay-gopalan) [inline vault/auth_token.go:341]: We can probably remove this right? :)

File: vault/auth_token.go [hunk 2]
```diff
@@ -276,14 +277,76 @@ func updateTokenFields(d *schema.ResourceData, data map[string]interface{}, crea
 }
 
 func readTokenFields(d *schema.ResourceData, resp *api.Secret) error {
-	for k, v := range getCommonTokenFieldMap(resp) {
+	handlers := map[string]fieldHandlerFunc{
```
Comment (vinay-gopalan) [inline vault/auth_token.go:280]: Nice!

File: vault/auth_token.go [hunk 3]
```diff
@@ -117,7 +118,7 @@ func addTokenFields(fields map[string]*schema.Schema, config *addTokenFieldsConf
 	}
 }
 
-func setTokenFields(d *schema.ResourceData, data map[string]interface{}, config *addTokenFieldsConfig) {
+func addRequestTokenFields(d *schema.ResourceData, data map[string]interface{}, config *addTokenFieldsConfig) {
```
Comment (vinay-gopalan) [inline vault/auth_token.go:121]: I noticed that after renaming, we're not using this function anymore. Is it safe to remove this?

Comment (benashz) [reply vault/auth_token.go:121]: Yeah, that was not the idea... Reverting.

Comment (benashz) [reply vault/auth_token.go:121]: I meant to hold that change back, but part of it slipped through.

Comment (vinay-gopalan) [reply vault/auth_token.go:121]: Ah I think I uncovered a bug, we would also need to update line 120 of `resource_token_auth_backend_role.go` where `setTokenFields` is being called instead of `addRequestTokenFields`. That also causes the tests to fail.

Tests are green once that line is fixed though! :)

Comment (benashz) [reply vault/auth_token.go]: Fixed in https://github.com/hashicorp/terraform-provider-vault/pull/1346/commits/baaa0f8bd6315462c4bacc5c455bf2232fabc2f7

Comment (benashz) [reply vault/auth_token.go]: I reverted it in the mean time, since it was rather unrelated to this fix.

File: vault/auth_token.go (hunk 1 above)
Comment (benashz) [reply vault/auth_token.go]: Fixed in https://github.com/hashicorp/terraform-provider-vault/pull/1346/commits/4c4d954fb4994302ffd3a5f5b8477b4c30abda2b

File: vault/auth_token.go (hunk 3 above)
Comment (vinay-gopalan) [reply vault/auth_token.go]: Nice, thanks!

**Review by vinay-gopalan — APPROVED** [review]
LGTM!

**Comment by benashz** [comment]
Root cause can be found here: https://github.com/hashicorp/terraform-provider-vault/pull/1346

**Comment by rgevaert** [comment]
I would love t see this merged!

**Review by vinay-gopalan — APPROVED** [review]
LGTM!

**Comment by rgevaert** [comment]
thanks @benashz looking forward to test drive this asap!
