### PR TITLE
Fix persistent diff for kubernetes_ca_cert in k8s-auth-config

### LINKED ISSUE #904: vault_kubernetes_auth_backend_config tries to remove kubernetes_ca_cert field on subsequent applies
### Terraform Version
```console
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/vault v2.15.0
```

### Affected Resource(s)
`vault_kubernetes_auth_backend_config`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
##### Kubernetes authentication backend
resource "vault_auth_backend" "kubernetes" {
  type        = "kubernetes"
 }

resource "vault_kubernetes_auth_backend_config" "cluster" {
  backend         = vault_auth_backend.kubernetes.path
  kubernetes_host = "https://kubernetes.default"
}
```

### Debug Output
```console
Terraform will perform the following actions:

  # module.vault.vault_kubernetes_auth_backend_config.cluster will be updated in-place
  ~ resource "vault_kubernetes_auth_backend_config" "cluster" {
        backend                = "kubernetes"
        disable_iss_validation = false
        disable_local_ca_jwt   = false
        id                     = "auth/kubernetes/config"
      - kubernetes_ca_cert     = <<~EOT
            -----BEGIN CERTIFICATE-----
            MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
            a3ViZUNBMB4XDTIwMTAyNTIyMjc1MVoXDTMwMTAyNDIyMjc1MVowFTETMBEGA1UE
            AxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANMO
            DKBT6BfinQg2LZFlZ1MYUTCmYSHgxP66dVhyhGLc3v0wpoRYym3sgnEfFC01IphE
            JbCxhGfV9/5/uzmMAyJbhgJ16xTccpuQetMltihiKt2vjFrXLaUmOpqnNzCXD4ly
            GFT7IRK6HaOqnjUscFFv5HeAn+lqufhm5cE1b0C97UMqtHAMYTSA8yWMAvzHdct1
            wyJOelCi23hKbzeo93JPdJlXaXxv5dcliBTE/wSQGYSU8LIdEi9zes9VsyVEn9Nh
            qL0KQQYwi6SRDsGK/mWbv3tih3l09PUzlz0V9TCwkt8iZt4iSDGcKWfrZ6vyV7wl
            9ZDNYqOQlSlK9GogjWMCAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW
            MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
            BBRsf/ByY9va3vwCz3bRf4OFlY62RDANBgkqhkiG9w0BAQsFAAOCAQEAUw+PoKz/
            bGj4q4Ml+TcYLgOQQWRXT7F7ZYBmOxv/IZ7iE83sGAoy+Y2dacr/IZYAFmbH+DgU
            sIKENpAiRHlkBk8j1PEQUX0QL24e9oUDbdnnQKu0KwiwTUtMp9wk3KcP++DRH2Ql
            aJH+gfqbNzjkiL1NOMvnxUtP6j1gcIhaHfHG6iKPqzancnjWsioDS7VQMaGtMEu/
            KRUqIQEv+/DaC/bNYxhX01NK7FYBxaKk5PDW99yB8Una8cpgh0TdPkH0JK3MHI2B
            0MY8eboU54xeA99k1mWX0b9dyCx8Xn5p/r3gtg91jFXrBS87QJnNyvhadn7fQt1w
            rsqF5gNYth9k/Q==
            -----END CERTIFICATE-----
        EOT -> null
        kubernetes_host        = "https://kubernetes.default"
        pem_keys               = []
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
### Expected Behavior
After creating the Kubernetes authentication backend as described in the terraform config above, if I do a subsequent `terraform apply` with no additional changes, it tries to remove the `kubernetes_ca_cert` that Vault automatically added. It should not do so and instead adopt it

### Actual Behavior
It tries to remove the kubernetes_ca_cert when it should not

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform apply`

### Important Factoids
Current work around is to add a `lifecycle.ignore_changes` on the `kubernetes_ca_cert` field
If it can't be done within the provider, then a documentation update about this would suffice

### PR DESCRIPTION
**Pull request by benashz**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #904 

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vault/blob/master/CHANGELOG.md):

```release-note

```

Output from acceptance testing:

```
$ make testacc TESTARGS='-v -test.run TestAccKubernetesAuth'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test -v -v -test.run TestAccKubernetesAuth -timeout 30m ./...

[...]

ok      github.com/hashicorp/terraform-provider-vault/util      (cached) [no tests to run]
=== RUN   TestAccKubernetesAuthBackendConfigDataSource_basic
--- PASS: TestAccKubernetesAuthBackendConfigDataSource_basic (3.32s)
=== RUN   TestAccKubernetesAuthBackendConfigDataSource_full
--- PASS: TestAccKubernetesAuthBackendConfigDataSource_full (3.05s)
=== RUN   TestAccKubernetesAuthBackendRoleDataSource_basic
--- PASS: TestAccKubernetesAuthBackendRoleDataSource_basic (1.82s)
=== RUN   TestAccKubernetesAuthBackendRoleDataSource_full
--- PASS: TestAccKubernetesAuthBackendRoleDataSource_full (1.79s)
=== RUN   TestAccKubernetesAuthBackendConfig_import
--- PASS: TestAccKubernetesAuthBackendConfig_import (13.00s)
=== RUN   TestAccKubernetesAuthBackendConfig_basic
--- PASS: TestAccKubernetesAuthBackendConfig_basic (1.75s)
=== RUN   TestAccKubernetesAuthBackendConfig_update
--- PASS: TestAccKubernetesAuthBackendConfig_update (3.05s)
=== RUN   TestAccKubernetesAuthBackendConfig_full
--- PASS: TestAccKubernetesAuthBackendConfig_full (1.74s)
=== RUN   TestAccKubernetesAuthBackendConfig_fullUpdate
--- PASS: TestAccKubernetesAuthBackendConfig_fullUpdate (4.38s)
=== RUN   TestAccKubernetesAuthBackendConfig_localCA
--- PASS: TestAccKubernetesAuthBackendConfig_localCA (3.00s)
=== RUN   TestAccKubernetesAuthBackendRole_import
--- PASS: TestAccKubernetesAuthBackendRole_import (2.16s)
=== RUN   TestAccKubernetesAuthBackendRole_basic
--- PASS: TestAccKubernetesAuthBackendRole_basic (1.72s)
=== RUN   TestAccKubernetesAuthBackendRole_update
--- PASS: TestAccKubernetesAuthBackendRole_update (3.10s)
=== RUN   TestAccKubernetesAuthBackendRole_full
--- PASS: TestAccKubernetesAuthBackendRole_full (1.71s)
=== RUN   TestAccKubernetesAuthBackendRole_fullUpdate
--- PASS: TestAccKubernetesAuthBackendRole_fullUpdate (6.91s)
PASS
ok      github.com/hashicorp/terraform-provider-vault/vault     56.008s

...
```

### CODE REVIEW

File: vault/resource_kubernetes_auth_backend_config_test.go [hunk 1]
```diff
@@ -342,8 +342,58 @@ func TestAccKubernetesAuthBackendConfig_fullUpdate(t *testing.T) {
 	})
 }
 
-func testAccKubernetesAuthBackendConfigConfig_basic(backend, jwt string) string {
-	return fmt.Sprintf(`
+func TestAccKubernetesAuthBackendConfig_localCA(t *testing.T) {
```
Comment (vinay-gopalan) [inline vault/resource_kubernetes_auth_backend_config_test.go:345]: This test fails when I run it with the error `one of pem_keys or kubernetes_ca_cert must be set`. Since we're passing `""` in `testAccKubernetesAuthBackendConfigConfig_basic`, looks like we're not setting either. I added the suggestion below to my file and the tests passed for me

File: vault/resource_kubernetes_auth_backend_config_test.go [hunk 2]
```diff
@@ -352,13 +402,20 @@ resource "vault_auth_backend" "kubernetes" {
...
-  kubernetes_ca_cert = %q
   token_reviewer_jwt = %q
-}`, backend, kubernetesCAcert, jwt)
+`, backend, jwt)
+
+	if ca != "" {
+		config += fmt.Sprintf(`
+  kubernetes_ca_cert = %q
+`, ca)
+	}
```
Comment (vinay-gopalan) [inline vault/resource_kubernetes_auth_backend_config_test.go:412]:
```suggestion
	} else {
		config += fmt.Sprintf(`
pem_keys = %q
`, []string{kubernetesPEMfile})
	}
```

**Review by vinay-gopalan — COMMENTED** [review]
Looking good! Encountered a failing test when running locally, and left a suggested change

File: vault/resource_kubernetes_auth_backend_config_test.go (hunk 1 above)
Comment (vinay-gopalan) [reply vault/resource_kubernetes_auth_backend_config_test.go:345]: Resolving since this looks to be fixed in v1.9.3

File: vault/resource_kubernetes_auth_backend_config_test.go (hunk 2 above)
Comment (vinay-gopalan) [reply vault/resource_kubernetes_auth_backend_config_test.go:412]: Resolving since this looks to be fixed in v1.9.3

Comment (benashz) [reply vault/resource_kubernetes_auth_backend_config_test.go:412]: Seems to break when testing against `1.9.{0..2}+ent`, but works fine on `1.9.3+ent`
